---
# Github repository is cloned every day on Gitlab.com
# https://gitlab.com/MrCerealGuy/Stonecraft
# Pipelines URL: https://gitlab.com/MrCerealGuy/Stonecraft/pipelines

stages:
  - build
  - package
  - deploy

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH

.build_template:
  stage: build
  script:
    - mkdir cmakebuild
    - mkdir -p artifact/stonecraft/usr/
    - cd cmakebuild
    - cmake -DCMAKE_INSTALL_PREFIX=../artifact/stonecraft/usr/ -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENT=TRUE -DENABLE_GETTEXT=TRUE -DENABLE_FREETYPE=TRUE -DENABLE_LEVELDB=FALSE -DENABLE_REDIS=FALSE -DRUN_IN_PLACE=TRUE ..
    - make -j2
    - make install
  artifacts:
    when: on_success
    expire_in: 1h
    paths:
      - artifact/*

.debpkg_template:
  stage: package
  before_script:
    - apt-get update -y
    - apt-get install -y git
    - mkdir -p build/deb/stonecraft/DEBIAN/
    - cp misc/debpkg-control build/deb/stonecraft/DEBIAN/control
    - cp -a artifact/stonecraft/usr build/deb/stonecraft/
  script:
    - rm -Rf build/deb/stonecraft/usr/share/stonecraft/games/stonecraft/.git
    - sed -i 's/DATEPLACEHOLDER/'$(date +%y.%m.%d)'/g' build/deb/stonecraft/DEBIAN/control
    - sed -i 's/LEVELDB_PLACEHOLDER/'$LEVELDB_PKG'/g' build/deb/stonecraft/DEBIAN/control
    - cd build/deb/ && dpkg-deb -b stonecraft/ && mv stonecraft.deb ../../
  artifacts:
    expire_in: 90 day
    paths:
      - ./*.deb

.debpkg_install:
  stage: deploy
  before_script:
    - apt-get update -y
  script:
    - apt-get install -y ./*.deb
    - stonecraft --version

##
## Debian
##

# Stretch

build:debian-9:
 extends: .build_template
 image: debian:9
 before_script:
   - apt-get update -y
   - apt-get -y install build-essential libirrlicht-dev cmake libbz2-dev libpng-dev libjpeg-dev libxxf86vm-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev

package:debian-9:
  extends: .debpkg_template
  image: debian:9
  needs:
    - build:debian-9
  variables:
    LEVELDB_PKG: libleveldb1v5

deploy:debian-9:
  extends: .debpkg_install
  image: debian:9
  needs:
    - package:debian-9

# Buster

build:debian-10:
 extends: .build_template
 image: debian:10
 before_script:
   - apt-get update -y
   - apt-get -y install build-essential libirrlicht-dev cmake libbz2-dev libpng-dev libjpeg-dev libxxf86vm-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev

package:debian-10:
  extends: .debpkg_template
  image: debian:10
  needs:
    - build:debian-10
  variables:
    LEVELDB_PKG: libleveldb1d

deploy:debian-10:
  extends: .debpkg_install
  image: debian:10
  needs:
    - package:debian-10

##
## Ubuntu
##

# Xenial

build:ubuntu-16.04:
  extends: .build_template
  image: ubuntu:xenial
  before_script:
    - apt-get update -y
    - apt-get -y install build-essential libirrlicht-dev cmake libbz2-dev libpng-dev libjpeg-dev libxxf86vm-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev

package:ubuntu-16.04:
  extends: .debpkg_template
  image: ubuntu:xenial
  needs:
    - build:ubuntu-16.04
  variables:
    LEVELDB_PKG: libleveldb1v5

deploy:ubuntu-16.04:
  extends: .debpkg_install
  image: ubuntu:xenial
  needs:
    - package:ubuntu-16.04

# Bionic

build:ubuntu-18.04:
  extends: .build_template
  image: ubuntu:bionic
  before_script:
    - apt-get update -y
    - apt-get -y install build-essential libirrlicht-dev cmake libbz2-dev libpng-dev libjpeg-dev libxxf86vm-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev

package:ubuntu-18.04:
  extends: .debpkg_template
  image: ubuntu:bionic
  needs:
    - build:ubuntu-18.04
  variables:
    LEVELDB_PKG: libleveldb1v5

deploy:ubuntu-18.04:
  extends: .debpkg_install
  image: ubuntu:bionic
  needs:
    - package:ubuntu-18.04

##
## Fedora
##

# Fedora 28 <-> RHEL 8
build:fedora-28:
  extends: .build_template
  image: fedora:28
  before_script:
    - dnf -y install make automake gcc gcc-c++ kernel-devel cmake libcurl-devel openal-soft-devel libvorbis-devel libXxf86vm-devel libogg-devel freetype-devel mesa-libGL-devel zlib-devel jsoncpp-devel irrlicht-devel gmp-devel sqlite-devel luajit-devel leveldb-devel ncurses-devel spatialindex-devel

##
## MinGW for Windows
##

.generic_win_template:
  image: ubuntu:bionic
  before_script:
    - apt-get update -y
    - apt-get install -y wget xz-utils unzip git cmake gettext
    - wget -nv http://minetest.kitsunemimi.pw/mingw-w64-${WIN_ARCH}_9.2.0_ubuntu18.04.tar.xz -O mingw.tar.xz
    - tar -xaf mingw.tar.xz -C /usr

.build_win_template:
  extends: .generic_win_template
  stage: build
  artifacts:
    expire_in: 1h
    paths:
      - build/*

.package_win_template:
  extends: .generic_win_template
  stage: package
  script:
    - cd build/stonecraft/_build
    - make package
    - cd ../../../
    - mkdir stonecraft-win-${WIN_ARCH}
    - unzip build/stonecraft/_build/stonecraft-*-win*.zip -d stonecraft-win-${WIN_ARCH}
    - cp /usr/${WIN_ARCH}-w64-mingw32/bin/libgcc*.dll stonecraft-win-${WIN_ARCH}/stonecraft-*-win*/bin
    - cp /usr/${WIN_ARCH}-w64-mingw32/bin/libstdc++*.dll stonecraft-win-${WIN_ARCH}/stonecraft-*-win*/bin
    - cp /usr/${WIN_ARCH}-w64-mingw32/bin/libwinpthread*.dll stonecraft-win-${WIN_ARCH}/stonecraft-*-win*/bin
  artifacts:
    expire_in: 90 day
    paths:
      - stonecraft-win-*/*

build:win32:
  extends: .build_win_template
  script:
    - ./util/buildbot/buildwin32.sh build
  variables:
    WIN_ARCH: "i686"

package:win32:
  extends: .package_win_template
  needs:
    - build:win32
  variables:
    WIN_ARCH: "i686"


build:win64:
  extends: .build_win_template
  script:
    - ./util/buildbot/buildwin64.sh build
  variables:
    WIN_ARCH: "x86_64"

package:win64:
  extends: .package_win_template
  needs:
    - build:win64
  variables:
    WIN_ARCH: "x86_64"

##
## Docker
##

package:docker:
  stage: package
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build . -t ${CONTAINER_IMAGE}/server:$CI_COMMIT_SHA -t ${CONTAINER_IMAGE}/server:$CI_COMMIT_REF_NAME -t ${CONTAINER_IMAGE}/server:latest
    - docker push ${CONTAINER_IMAGE}/server:$CI_COMMIT_SHA
    - docker push ${CONTAINER_IMAGE}/server:$CI_COMMIT_REF_NAME
    - docker push ${CONTAINER_IMAGE}/server:latest

##
## Gitlab Pages (Lua API documentation)
##

pages:
  stage: deploy
  image: python:3.8
  before_script:
    - pip install git+https://github.com/Python-Markdown/markdown.git
    - pip install git+https://github.com/mkdocs/mkdocs.git
    - pip install pygments
  script:
    - cd doc/mkdocs && ./build.sh
  artifacts:
    paths:
      - public
  only:
    - master

##
## AppImage
##

package:appimage-client:
  stage: package
  image: appimagecrafters/appimage-builder
  needs:
    - build:ubuntu-18.04
  before_script:
    - apt-get update -y
    - apt-get install -y git wget
    # Collect files
    - mkdir AppDir
    - cp -a artifact/minetest/usr/ AppDir/usr/
    - rm AppDir/usr/bin/minetestserver
    - cp -a clientmods AppDir/usr/share/stonecraft
  script:
    - git clone $MINETEST_GAME_REPO AppDir/usr/share/minetest/games/minetest_game
    - rm -rf AppDir/usr/share/stonecraft/games/stonecraft/.git
    - export VERSION=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    # Remove PrefersNonDefaultGPU property due to validation errors
    - sed -i '/PrefersNonDefaultGPU/d' AppDir/usr/share/applications/net.minetest.minetest.desktop
    - appimage-builder --skip-test
  artifacts:
    expire_in: 90 day
    paths:
      - ./*.AppImage
