/* WARNING: This file was automatically generated by lua2c. */

#ifdef __cplusplus
extern "C" {
#endif
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#ifdef __cplusplus
}
#endif
#include <stdio.h>
#include <stdlib.h>


#include <string.h>


#include <assert.h>

/* function(itemstack, user, pointed_thing) */
static int lcf10 (lua_State * L) {
  enum { lc_nformalargs = 3 };
  lua_settop(L,3);
  
  /* if pointed_thing.type ~= "node" then */
  enum { lc1 = 3 };
  lua_pushliteral(L,"type");
  lua_gettable(L,3);
  lua_pushliteral(L,"node");
  const int lc2 = lua_equal(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc2);
  lua_pushboolean(L,!(lua_toboolean(L,-1)));
  lua_remove(L,-2);
  const int lc3 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc3) {
    
    /* return */
    return 0;
    assert(lua_gettop(L) == 3);
  }
  lua_settop(L,lc1);
  assert(lua_gettop(L) == 3);
  
  /* -- Check if node protected
   * if minetest.is_protected(pointed_thing.under, user:get_player_name()) then */
  enum { lc4 = 3 };
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"is_protected");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  const int lc5 = lua_gettop(L);
  lua_pushliteral(L,"under");
  lua_gettable(L,3);
  lua_pushvalue(L,2);
  lua_pushliteral(L,"get_player_name");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,LUA_MULTRET);
  lua_call(L,(lua_gettop(L) - lc5),1);
  const int lc6 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc6) {
    
    /* return */
    return 0;
    assert(lua_gettop(L) == 3);
  }
  lua_settop(L,lc4);
  assert(lua_gettop(L) == 3);
  
  /* local pos = pointed_thing.under */
  lua_pushliteral(L,"under");
  lua_gettable(L,3);
  assert(lua_gettop(L) == 4);
  
  /* local nn = minetest.get_node(pos).name */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"get_node");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushvalue(L,4);
  lua_call(L,1,1);
  lua_pushliteral(L,"name");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  assert(lua_gettop(L) == 5);
  
  /* -- Is node dirt, sand or gravel
   * if minetest.get_item_group(nn, "crumbly") > 0 then */
  enum { lc7 = 5 };
  lua_pushnumber(L,0);
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"get_item_group");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushvalue(L,5);
  lua_pushliteral(L,"crumbly");
  lua_call(L,2,1);
  const int lc8 = lua_lessthan(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc8);
  const int lc9 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc9) {
    
    /* local inv = user:get_inventory() */
    lua_pushvalue(L,2);
    lua_pushliteral(L,"get_inventory");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_call(L,1,1);
    assert(lua_gettop(L) == 6);
    
    /* minetest.remove_node(pointed_thing.under) */
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"remove_node");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushliteral(L,"under");
    lua_gettable(L,3);
    lua_call(L,1,0);
    assert(lua_gettop(L) == 6);
    
    /* nodeupdate(pos) */
    lua_getfield(L,LUA_ENVIRONINDEX,"nodeupdate");
    lua_pushvalue(L,4);
    lua_call(L,1,0);
    assert(lua_gettop(L) == 6);
    
    /* inv:add_item("main", {name = nn}) */
    lua_pushvalue(L,6);
    lua_pushliteral(L,"add_item");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_pushliteral(L,"main");
    lua_createtable(L,0,1);
    lua_pushliteral(L,"name");
    lua_pushvalue(L,5);
    lua_rawset(L,-3);
    lua_call(L,3,0);
    assert(lua_gettop(L) == 6);
    
    /* itemstack:add_wear(65535 / 100) */
    lua_pushvalue(L,1);
    lua_pushliteral(L,"add_wear");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_pushnumber(L,655.35);
    lua_call(L,2,0);
    assert(lua_gettop(L) == 6);
    
    /* -- 111 uses
     * minetest.sound_play("default_dirt_footstep", {pos = pos, gain = 0.35}) */
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"sound_play");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushliteral(L,"default_dirt_footstep");
    lua_createtable(L,0,2);
    lua_pushliteral(L,"pos");
    lua_pushvalue(L,4);
    lua_rawset(L,-3);
    lua_pushliteral(L,"gain");
    lua_pushnumber(L,0.35);
    lua_rawset(L,-3);
    lua_call(L,2,0);
    assert(lua_gettop(L) == 6);
    
    /* return itemstack */
    lua_pushvalue(L,1);
    return 1;
    assert(lua_gettop(L) == 6);
  }
  lua_settop(L,lc7);
  assert(lua_gettop(L) == 5);
  return 0;
}


/* function(itemstack, user, pointed_thing) */
static int lcf14 (lua_State * L) {
  enum { lc_nformalargs = 3 };
  lua_settop(L,3);
  
  /* if user:get_breath() < 10 then */
  enum { lc11 = 3 };
  lua_pushvalue(L,2);
  lua_pushliteral(L,"get_breath");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  lua_pushnumber(L,10);
  const int lc12 = lua_lessthan(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc12);
  const int lc13 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc13) {
    
    /* user:set_breath(10) */
    lua_pushvalue(L,2);
    lua_pushliteral(L,"set_breath");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_pushnumber(L,10);
    lua_call(L,2,0);
    assert(lua_gettop(L) == 3);
  }
  lua_settop(L,lc11);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* name: (main)
 * function(...) */
static int lcf_main (lua_State * L) {
  enum { lc_nformalargs = 0 };
  const int lc_nactualargs = lua_gettop(L);
  const int lc_nextra = (lc_nactualargs - lc_nformalargs);
  
  /* local S = ethereal.intllib */
  lua_getfield(L,LUA_ENVIRONINDEX,"ethereal");
  lua_pushliteral(L,"intllib");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Crystal Spike (Hurts if you touch it - thanks to ZonerDarkRevention for his DokuCraft DeviantArt crystal texture)
   * minetest.register_node("ethereal:crystal_spike", {
   * 	description = S("Crystal Spike"),
   * 	drawtype = "plantlike",
   * 	tiles = { "crystal_spike.png" },
   * 	inventory_image = "crystal_spike.png",
   * 	wield_image = "crystal_spike.png",
   * 	paramtype = "light",
   * 	light_source = 7,
   * 	sunlight_propagates = true,
   * 	walkable = false,
   * 	damage_per_second = 1,
   * 	groups = {cracky = 1, falling_node = 1, puts_out_fire = 1},
   * 	sounds = default.node_sound_glass_defaults(),
   * 	selection_box = {
   * 		type = "fixed",
   * 		fixed = {-0.5, -0.5, -0.5, 0.5, -5/16, 0.5},
   * 	},
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_node");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:crystal_spike");
  lua_createtable(L,0,13);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Crystal Spike");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"drawtype");
  lua_pushliteral(L,"plantlike");
  lua_rawset(L,-3);
  lua_pushliteral(L,"tiles");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"crystal_spike.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"crystal_spike.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"crystal_spike.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"paramtype");
  lua_pushliteral(L,"light");
  lua_rawset(L,-3);
  lua_pushliteral(L,"light_source");
  lua_pushnumber(L,7);
  lua_rawset(L,-3);
  lua_pushliteral(L,"sunlight_propagates");
  lua_pushboolean(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"walkable");
  lua_pushboolean(L,0);
  lua_rawset(L,-3);
  lua_pushliteral(L,"damage_per_second");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"groups");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"cracky");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"falling_node");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"puts_out_fire");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"sounds");
  lua_getfield(L,LUA_ENVIRONINDEX,"default");
  lua_pushliteral(L,"node_sound_glass_defaults");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_call(L,0,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"selection_box");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"fixed");
  lua_rawset(L,-3);
  lua_pushliteral(L,"fixed");
  lua_createtable(L,6,0);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,1);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,3);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,4);
  lua_pushnumber(L,-0.3125);
  lua_rawseti(L,-2,5);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,6);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Crystal Ingot
   * minetest.register_craftitem("ethereal:crystal_ingot", {
   * 	description = S("Crystal Ingot"),
   * 	inventory_image = "crystal_ingot.png",
   * 	wield_image = "crystal_ingot.png",
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craftitem");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Crystal Ingot");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"crystal_ingot.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"crystal_ingot.png");
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* minetest.register_craft({
   * 	output = "ethereal:crystal_ingot",
   * 	recipe = {
   * 		{"default:mese_crystal", "ethereal:crystal_spike"},
   * 		{"ethereal:crystal_spike", "default:mese_crystal"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,2,0);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"default:mese_crystal");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:crystal_spike");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,1);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"ethereal:crystal_spike");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:mese_crystal");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,2);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Crystal Block
   * minetest.register_node("ethereal:crystal_block", {
   * 	description = S("Crystal Block"),
   * 	tiles = {"crystal_block.png"},
   * 	light_source = 9,
   * 	is_ground_content = false,
   * 	groups = {cracky = 1, level = 2, puts_out_fire = 1},
   * 	sounds = default.node_sound_glass_defaults(),
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_node");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:crystal_block");
  lua_createtable(L,0,6);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Crystal Block");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"tiles");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"crystal_block.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"light_source");
  lua_pushnumber(L,9);
  lua_rawset(L,-3);
  lua_pushliteral(L,"is_ground_content");
  lua_pushboolean(L,0);
  lua_rawset(L,-3);
  lua_pushliteral(L,"groups");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"cracky");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"level");
  lua_pushnumber(L,2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"puts_out_fire");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"sounds");
  lua_getfield(L,LUA_ENVIRONINDEX,"default");
  lua_pushliteral(L,"node_sound_glass_defaults");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_call(L,0,1);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* minetest.register_craft({
   * 	output = "ethereal:crystal_block",
   * 	recipe = {
   * 		{"ethereal:crystal_ingot", "ethereal:crystal_ingot", "ethereal:crystal_ingot"},
   * 		{"ethereal:crystal_ingot", "ethereal:crystal_ingot", "ethereal:crystal_ingot"},
   * 		{"ethereal:crystal_ingot", "ethereal:crystal_ingot", "ethereal:crystal_ingot"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:crystal_block");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,2);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* minetest.register_craft({
   * 	output = "ethereal:crystal_ingot 9",
   * 	recipe = {
   * 		{"ethereal:crystal_block"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:crystal_ingot 9");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,1,0);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"ethereal:crystal_block");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Crystal Sword (Powerful wee beastie)
   * minetest.register_tool("ethereal:sword_crystal", {
   * 	description = S("Crystal Sword"),
   * 	inventory_image = "crystal_sword.png",
   * 	wield_image = "crystal_sword.png",
   * 	tool_capabilities = {
   * 		full_punch_interval = 0.6,
   * 		max_drop_level = 1,
   * 		groupcaps = {
   * 			snappy = {
   * 				times = {[1] = 1.70, [2] = 0.70, [3] = 0.25},
   * 				uses = 50,
   * 				maxlevel = 3
   * 			},
   * 		},
   * 		damage_groups = {fleshy = 10},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_tool");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:sword_crystal");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Crystal Sword");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"crystal_sword.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"crystal_sword.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"tool_capabilities");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"full_punch_interval");
  lua_pushnumber(L,0.6);
  lua_rawset(L,-3);
  lua_pushliteral(L,"max_drop_level");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"groupcaps");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"snappy");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"times");
  lua_createtable(L,0,3);
  lua_pushnumber(L,1);
  lua_pushnumber(L,1.7);
  lua_rawset(L,-3);
  lua_pushnumber(L,2);
  lua_pushnumber(L,0.7);
  lua_rawset(L,-3);
  lua_pushnumber(L,3);
  lua_pushnumber(L,0.25);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"uses");
  lua_pushnumber(L,50);
  lua_rawset(L,-3);
  lua_pushliteral(L,"maxlevel");
  lua_pushnumber(L,3);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"damage_groups");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"fleshy");
  lua_pushnumber(L,10);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* minetest.register_craft({
   * 	output = "ethereal:sword_crystal",
   * 	recipe = {
   * 		{"ethereal:crystal_ingot"},
   * 		{"ethereal:crystal_ingot"},
   * 		{"default:steel_ingot"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:sword_crystal");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,1);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,2);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"default:steel_ingot");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Crystal Axe
   * minetest.register_tool("ethereal:axe_crystal", {
   * 	description = S("Crystal Axe"),
   * 	inventory_image = "crystal_axe.png",
   * 	wield_image = "crystal_axe.png",
   * 	tool_capabilities = {
   * 		full_punch_interval = 0.8,
   * 		max_drop_level = 1,
   * 		groupcaps = {
   * 			choppy = {
   * 				times = {[1] = 2.00, [2] = 0.80, [3] = 0.40},
   * 				uses = 30,
   * 				maxlevel = 2
   * 			},
   * 		},
   * 		damage_groups = {fleshy = 7},
   * 	},
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_tool");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:axe_crystal");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Crystal Axe");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"crystal_axe.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"crystal_axe.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"tool_capabilities");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"full_punch_interval");
  lua_pushnumber(L,0.8);
  lua_rawset(L,-3);
  lua_pushliteral(L,"max_drop_level");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"groupcaps");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"choppy");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"times");
  lua_createtable(L,0,3);
  lua_pushnumber(L,1);
  lua_pushnumber(L,2);
  lua_rawset(L,-3);
  lua_pushnumber(L,2);
  lua_pushnumber(L,0.8);
  lua_rawset(L,-3);
  lua_pushnumber(L,3);
  lua_pushnumber(L,0.4);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"uses");
  lua_pushnumber(L,30);
  lua_rawset(L,-3);
  lua_pushliteral(L,"maxlevel");
  lua_pushnumber(L,2);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"damage_groups");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"fleshy");
  lua_pushnumber(L,7);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* minetest.register_craft({
   * 	output = 'ethereal:axe_crystal',
   * 	recipe = {
   * 		{'ethereal:crystal_ingot', 'ethereal:crystal_ingot'},
   * 		{'ethereal:crystal_ingot', 'default:steel_ingot'},
   * 		{'', 'default:steel_ingot'},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:axe_crystal");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,1);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:steel_ingot");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,2);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:steel_ingot");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Crystal Pick (This will last a while)
   * minetest.register_tool("ethereal:pick_crystal", {
   * 	description = S("Crystal Pickaxe"),
   * 	inventory_image = "crystal_pick.png",
   * 	wield_image = "crystal_pick.png",
   * 	tool_capabilities = {
   * 		full_punch_interval = 0.7,
   * 		max_drop_level = 3,
   * 		groupcaps={
   * 			cracky = {
   * 				times = {[1] = 1.8, [2] = 0.8, [3] = 0.40},
   * 				uses = 40,
   * 				maxlevel = 3
   * 			},
   * 		},
   * 		damage_groups = {fleshy = 7},
   * 	},
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_tool");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:pick_crystal");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Crystal Pickaxe");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"crystal_pick.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"crystal_pick.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"tool_capabilities");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"full_punch_interval");
  lua_pushnumber(L,0.7);
  lua_rawset(L,-3);
  lua_pushliteral(L,"max_drop_level");
  lua_pushnumber(L,3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"groupcaps");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"cracky");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"times");
  lua_createtable(L,0,3);
  lua_pushnumber(L,1);
  lua_pushnumber(L,1.8);
  lua_rawset(L,-3);
  lua_pushnumber(L,2);
  lua_pushnumber(L,0.8);
  lua_rawset(L,-3);
  lua_pushnumber(L,3);
  lua_pushnumber(L,0.4);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"uses");
  lua_pushnumber(L,40);
  lua_rawset(L,-3);
  lua_pushliteral(L,"maxlevel");
  lua_pushnumber(L,3);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"damage_groups");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"fleshy");
  lua_pushnumber(L,7);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* minetest.register_craft({
   * 	output = "ethereal:pick_crystal",
   * 	recipe = {
   * 		{"ethereal:crystal_ingot", "ethereal:crystal_ingot", "ethereal:crystal_ingot"},
   * 		{"", "default:steel_ingot", ""},
   * 		{"", "default:steel_ingot", ""},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:pick_crystal");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:steel_ingot");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,2);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:steel_ingot");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Crystal Shovel (with Soft Touch so player can dig up dirt with grass intact)
   * minetest.register_tool("ethereal:shovel_crystal", {
   * 	description = S("Crystal (soft touch) Shovel"),
   * 	inventory_image = "crystal_shovel.png",
   * 	wield_image = "crystal_shovel.png^[transformR90",
   * 
   * 	on_use = function(itemstack, user, pointed_thing)
   * 
   * 		if pointed_thing.type ~= "node" then
   * 			return
   * 		end
   * 
   * 		-- Check if node protected
   * 		if minetest.is_protected(pointed_thing.under, user:get_player_name()) then
   * 			return
   * 		end
   * 
   * 		local pos = pointed_thing.under
   * 		local nn = minetest.get_node(pos).name
   * 
   * 		-- Is node dirt, sand or gravel
   * 		if minetest.get_item_group(nn, "crumbly") > 0 then
   * 
   * 			local inv = user:get_inventory()
   * 
   * 			minetest.remove_node(pointed_thing.under)
   * 
   * 			nodeupdate(pos)
   * 
   * 			inv:add_item("main", {name = nn})
   * 			itemstack:add_wear(65535 / 100) -- 111 uses
   * 
   * 			minetest.sound_play("default_dirt_footstep", {pos = pos, gain = 0.35})
   * 
   * 			return itemstack
   * 		end
   * 	end,
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_tool");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:shovel_crystal");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Crystal (soft touch) Shovel");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"crystal_shovel.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"crystal_shovel.png^[transformR90");
  lua_rawset(L,-3);
  lua_pushliteral(L,"on_use");
  lua_pushcfunction(L,lcf10);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* minetest.register_craft({
   * 	output = "ethereal:shovel_crystal",
   * 	recipe = {
   * 		{"ethereal:crystal_ingot"},
   * 		{"default:steel_ingot"},
   * 		{"default:steel_ingot"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:shovel_crystal");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,1);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"default:steel_ingot");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,2);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"default:steel_ingot");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Crystal Gilly Staff (replenishes air supply when used)
   * minetest.register_tool("ethereal:crystal_gilly_staff", {
   * 	description = S("Crystal Gilly Staff"),
   * 	inventory_image = "crystal_gilly_staff.png",
   * 	wield_image = "crystal_gilly_staff.png",
   * 
   * 	on_use = function(itemstack, user, pointed_thing)
   * 		if user:get_breath() < 10 then
   * 			user:set_breath(10)
   * 		end
   * 	end,
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_tool");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:crystal_gilly_staff");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Crystal Gilly Staff");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"crystal_gilly_staff.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"crystal_gilly_staff.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"on_use");
  lua_pushcfunction(L,lcf14);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* minetest.register_craft({
   * 	output = "ethereal:crystal_gilly_staff",
   * 	recipe = {
   * 		{"ethereal:green_moss", "ethereal:gray_moss", "ethereal:fiery_moss"},
   * 		{"ethereal:crystal_moss", "ethereal:crystal_ingot", "ethereal:mushroom_moss"},
   * 		{"", "ethereal:crystal_ingot", ""},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:crystal_gilly_staff");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:green_moss");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:gray_moss");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:fiery_moss");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:crystal_moss");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:mushroom_moss");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,2);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:crystal_ingot");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  return 0;
}


/* from lua.c */
static int traceback (lua_State *L) {
  if (!lua_isstring(L, 1))  /* 'message' not a string? */
    return 1;  /* keep it intact */
  lua_getfield(L, LUA_GLOBALSINDEX, "debug");
  if (!lua_istable(L, -1)) {
    lua_pop(L, 1);
    return 1;
  }
  lua_getfield(L, -1, "traceback");
  if (!lua_isfunction(L, -1)) {
    lua_pop(L, 2);
    return 1;
  }
  lua_pushvalue(L, 1);  /* pass error message */
  lua_pushinteger(L, 2);  /* skip this function and traceback */
  lua_call(L, 2, 1);  /* call debug.traceback */
  return 1;
}


static void lc_l_message (const char *pname, const char *msg) {
  if (pname) fprintf(stderr, "%s: ", pname);
  fprintf(stderr, "%s\n", msg);
  fflush(stderr);
}

static int lc_report (lua_State *L, int status) {
  if (status && !lua_isnil(L, -1)) {
    const char *msg = lua_tostring(L, -1);
    if (msg == NULL) msg = "(error object is not a string)";
    /*FIX-IMROVE:progname*/
    lc_l_message("lua", msg);
    lua_pop(L, 1);
  }
  return status;
}

static int lc_docall (lua_State *L, int narg, int clear) {
  int status;
  int base = lua_gettop(L) - narg;  /* function index */
  lua_pushcfunction(L, traceback);  /* push traceback function */
  lua_insert(L, base);  /* put it under chunk and args */
  /*FIX? signal(SIGINT, laction); */
  status = lua_pcall(L, narg, (clear ? 0 : LUA_MULTRET), base);
  /*FIX? signal(SIGINT, SIG_DFL); */
  lua_remove(L, base);  /* remove traceback function */
  /* force a complete garbage collection in case of errors */
  if (status != 0) lua_gc(L, LUA_GCCOLLECT, 0);
  return status;
}

static int lc_dofile (lua_State *L, const char *name) {
  int status = luaL_loadfile(L, name) || lc_docall(L, 0, 1);
  return lc_report(L, status);
}

static int lc_dostring (lua_State *L, const char *s, const char *name) {
  int status = luaL_loadbuffer(L, s, strlen(s), name) || lc_docall(L, 0, 1);
  return lc_report(L, status);
}

static int lc_handle_luainit (lua_State *L) {
  const char *init = getenv(LUA_INIT);
  if (init == NULL) return 0;  /* status OK */
  else if (init[0] == '@')
    return lc_dofile(L, init+1);
  else
    return lc_dostring(L, init, "=" LUA_INIT);
}


typedef struct {
  int c;
  const char ** v;
} lc_args_t;


/* create global arg table */
static void lc_createarg(lua_State * L, const lc_args_t * const args) {
  int i;
  lua_newtable(L);
  for (i=0; i < args->c; i++) {
    lua_pushstring(L, args->v[i]);
    lua_rawseti(L, -2, i);
  }
  lua_setglobal(L, "arg");
}


int lc_pmain_mod_ethereal_crystal(lua_State * L) {
  luaL_openlibs(L);

  lua_pushcfunction(L, traceback);

  const int status1 = lc_handle_luainit(L);
  if (status1 != 0) return 0;

  /* note: IMPROVE: closure not always needed here */
  lua_newtable(L); /* closure table */
  lua_pushcclosure(L, lcf_main, 1);

  int status2 = lua_pcall(L, 0, 0, -2);
  if (status2 != 0) {
    const char * msg = lua_tostring(L,-1);
    if (msg == NULL) msg = "(error object is not a string)";
    fputs(msg, stderr);
  }
  return 0;
}


