/* WARNING: This file was automatically generated by lua2c. */

#ifdef __cplusplus
extern "C" {
#endif
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#ifdef __cplusplus
}
#endif
#include <stdio.h>
#include <stdlib.h>


#include <string.h>


#include <assert.h>

/* function(itemstack, user, pointed_thing) */
static int lcf17 (lua_State * L) {
  enum { lc_nformalargs = 3 };
  lua_settop(L,3);
  
  /* if pointed_thing.type ~= "node" then */
  enum { lc6 = 3 };
  lua_pushliteral(L,"type");
  lua_gettable(L,3);
  lua_pushliteral(L,"node");
  const int lc7 = lua_equal(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc7);
  lua_pushboolean(L,!(lua_toboolean(L,-1)));
  lua_remove(L,-2);
  const int lc8 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc8) {
    
    /* return */
    return 0;
    assert(lua_gettop(L) == 3);
  }
  lua_settop(L,lc6);
  assert(lua_gettop(L) == 3);
  
  /* local pos = pointed_thing.under */
  lua_pushliteral(L,"under");
  lua_gettable(L,3);
  assert(lua_gettop(L) == 4);
  
  /* local pname = user:get_player_name() */
  lua_pushvalue(L,2);
  lua_pushliteral(L,"get_player_name");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 5);
  
  /* if minetest.is_protected(pos, pname) then */
  enum { lc9 = 5 };
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"is_protected");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushvalue(L,4);
  lua_pushvalue(L,5);
  lua_call(L,2,1);
  const int lc10 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc10) {
    
    /* minetest.record_protection_violation(pos, pname) */
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"record_protection_violation");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushvalue(L,4);
    lua_pushvalue(L,5);
    lua_call(L,2,0);
    assert(lua_gettop(L) == 5);
    
    /* return */
    return 0;
    assert(lua_gettop(L) == 5);
  }
  lua_settop(L,lc9);
  assert(lua_gettop(L) == 5);
  
  /* local node = minetest.get_node(pos).name */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"get_node");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushvalue(L,4);
  lua_call(L,1,1);
  lua_pushliteral(L,"name");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  assert(lua_gettop(L) == 6);
  
  /* if node == "default:stone"
   * 		or node == "default:desert_stone" then */
  enum { lc11 = 6 };
  lua_pushvalue(L,6);
  lua_pushliteral(L,"default:stone");
  const int lc12 = lua_equal(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc12);
  if (!(lua_toboolean(L,-1))) {
    lua_pop(L,1);
    lua_pushvalue(L,6);
    lua_pushliteral(L,"default:desert_stone");
    const int lc13 = lua_equal(L,-2,-1);
    lua_pop(L,2);
    lua_pushboolean(L,lc13);
  }
  const int lc14 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc14) {
    
    /* minetest.swap_node(pos, {name = "ethereal:glostone"}) */
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"swap_node");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushvalue(L,4);
    lua_createtable(L,0,1);
    lua_pushliteral(L,"name");
    lua_pushliteral(L,"ethereal:glostone");
    lua_rawset(L,-3);
    lua_call(L,2,0);
    assert(lua_gettop(L) == 6);
    
    /* if not minetest.setting_getbool("creative_mode") then */
    enum { lc15 = 6 };
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"setting_getbool");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushliteral(L,"creative_mode");
    lua_call(L,1,1);
    lua_pushboolean(L,!(lua_toboolean(L,-1)));
    lua_remove(L,-2);
    const int lc16 = lua_toboolean(L,-1);
    lua_pop(L,1);
    if (lc16) {
      
      /* itemstack:add_wear(65535 / 149) */
      lua_pushvalue(L,1);
      lua_pushliteral(L,"add_wear");
      lua_gettable(L,-2);
      lua_insert(L,-2);
      lua_pushnumber(L,439.8322147651);
      lua_call(L,2,0);
      assert(lua_gettop(L) == 6);
    }
    lua_settop(L,lc15);
    assert(lua_gettop(L) == 6);
    
    /* return itemstack */
    lua_pushvalue(L,1);
    return 1;
    assert(lua_gettop(L) == 6);
  }
  lua_settop(L,lc11);
  assert(lua_gettop(L) == 6);
  return 0;
}


/* name: (main)
 * function(...) */
static int lcf_main (lua_State * L) {
  enum { lc_nformalargs = 0 };
  const int lc_nactualargs = lua_gettop(L);
  const int lc_nextra = (lc_nactualargs - lc_nformalargs);
  
  /* local S = ethereal.intllib */
  lua_getfield(L,LUA_ENVIRONINDEX,"ethereal");
  lua_pushliteral(L,"intllib");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Bamboo Flooring
   * minetest.register_node("ethereal:bamboo_floor", {
   * 	description = S("Bamboo Floor"),
   * 	drawtype = 'nodebox',
   * 	tiles = { "bamboo_floor.png" },
   * 	wield_image = "bamboo_floor.png",
   * 	inventory_image = "bamboo_floor.png",
   * 	paramtype = "light",
   * 	paramtype2 = "wallmounted",
   * 	walkable = true,
   * 	node_box = {
   * 		type = "wallmounted",
   * 		wall_top    = {-0.5, 0.4375, -0.5, 0.5, 0.5, 0.5},
   * 		wall_bottom = {-0.5, -0.5, -0.5, 0.5, -0.4375, 0.5},
   * 		wall_side   = {-0.5, -0.5, -0.5, -0.4375, 0.5, 0.5},
   * 	},
   * 	selection_box = {type = "wallmounted"},
   * 	groups = {snappy = 3, choppy = 3 , flammable = 2},
   * 	sounds = default.node_sound_wood_defaults(),
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_node");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:bamboo_floor");
  lua_createtable(L,0,12);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Bamboo Floor");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"drawtype");
  lua_pushliteral(L,"nodebox");
  lua_rawset(L,-3);
  lua_pushliteral(L,"tiles");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"bamboo_floor.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"bamboo_floor.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"bamboo_floor.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"paramtype");
  lua_pushliteral(L,"light");
  lua_rawset(L,-3);
  lua_pushliteral(L,"paramtype2");
  lua_pushliteral(L,"wallmounted");
  lua_rawset(L,-3);
  lua_pushliteral(L,"walkable");
  lua_pushboolean(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"node_box");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"wallmounted");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wall_top");
  lua_createtable(L,6,0);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,1);
  lua_pushnumber(L,0.4375);
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,3);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,4);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,5);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,6);
  lua_rawset(L,-3);
  lua_pushliteral(L,"wall_bottom");
  lua_createtable(L,6,0);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,1);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,3);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,4);
  lua_pushnumber(L,-0.4375);
  lua_rawseti(L,-2,5);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,6);
  lua_rawset(L,-3);
  lua_pushliteral(L,"wall_side");
  lua_createtable(L,6,0);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,1);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,3);
  lua_pushnumber(L,-0.4375);
  lua_rawseti(L,-2,4);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,5);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,6);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"selection_box");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"wallmounted");
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"groups");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"snappy");
  lua_pushnumber(L,3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"choppy");
  lua_pushnumber(L,3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"flammable");
  lua_pushnumber(L,2);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"sounds");
  lua_getfield(L,LUA_ENVIRONINDEX,"default");
  lua_pushliteral(L,"node_sound_wood_defaults");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_call(L,0,1);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Craft Bamboo into Bamboo Flooring
   * minetest.register_craft({
   * 	output = "ethereal:bamboo_floor 2",
   * 	recipe = {
   * 		{"ethereal:bamboo", "ethereal:bamboo", "ethereal:bamboo"},
   * 		{"ethereal:bamboo", "ethereal:bamboo", "ethereal:bamboo"},
   * 		{"ethereal:bamboo", "ethereal:bamboo", "ethereal:bamboo"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:bamboo_floor 2");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,2);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Craft Bamboo into Paper
   * minetest.register_craft({
   * 	output = "default:paper 6",
   * 	recipe = {
   * 		{"ethereal:bamboo", "ethereal:bamboo"},
   * 		{"ethereal:bamboo", "ethereal:bamboo"},
   * 		{"ethereal:bamboo", "ethereal:bamboo"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"default:paper 6");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,1);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,2);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:bamboo");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- X pattern craft recipes (5x 'a' in X pattern gives 5 of 'b')
   * local cheat = {
   * 	{"default:cobble", "default:gravel", 5},
   * 	{"default:gravel", "default:dirt", 5},
   * 	{"default:dirt", "default:sand", 5},
   * 	{"default:ice", "default:snow", 20},
   * 	{"ethereal:dry_dirt", "default:desert_sand", 5},
   * } */
  lua_createtable(L,5,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:cobble");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:gravel");
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,5);
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:gravel");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:dirt");
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,5);
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,2);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:dirt");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:sand");
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,5);
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,3);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:ice");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:snow");
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,20);
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,4);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:dry_dirt");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:desert_sand");
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,5);
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,5);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* for n = 1, #cheat do */
  lua_pushnumber(L,1);
  const double lc4 = lua_objlen(L,(2 + lc_nextra));
  lua_pushnumber(L,lc4);
  if (!((lua_isnumber(L,-2) && lua_isnumber(L,-1)))) {
    luaL_error(L,"'for' limit must be a number");
  }
  double lc1_var = lua_tonumber(L,-2);
  const double lc2_limit = lua_tonumber(L,-1);
  const double lc3_step = 1;
  lua_pop(L,2);
  enum { lc5 = 2 };
  while ((((lc3_step > 0) && (lc1_var <= lc2_limit)) || ((lc3_step <= 0) && (lc1_var >= lc2_limit)))) {
    
    /* internal: local n at index 3 */
    lua_pushnumber(L,lc1_var);
    
    /* minetest.register_craft({
     * 		output = cheat[n][2] .. " " .. cheat[n][3],
     * 		recipe = {
     * 			{cheat[n][1], "", cheat[n][1]},
     * 			{"", cheat[n][1], ""},
     * 			{cheat[n][1], "", cheat[n][1]},
     * 		}
     * 	}) */
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"register_craft");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_createtable(L,0,2);
    lua_pushliteral(L,"output");
    lua_pushvalue(L,(3 + lc_nextra));
    lua_gettable(L,(2 + lc_nextra));
    lua_pushnumber(L,2);
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushliteral(L," ");
    lua_pushvalue(L,(3 + lc_nextra));
    lua_gettable(L,(2 + lc_nextra));
    lua_pushnumber(L,3);
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_concat(L,2);
    lua_concat(L,2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"recipe");
    lua_createtable(L,3,0);
    lua_createtable(L,3,0);
    lua_pushvalue(L,(3 + lc_nextra));
    lua_gettable(L,(2 + lc_nextra));
    lua_pushnumber(L,1);
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_rawseti(L,-2,1);
    lua_pushliteral(L,"");
    lua_rawseti(L,-2,2);
    lua_pushvalue(L,(3 + lc_nextra));
    lua_gettable(L,(2 + lc_nextra));
    lua_pushnumber(L,1);
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_rawseti(L,-2,3);
    lua_rawseti(L,-2,1);
    lua_createtable(L,3,0);
    lua_pushliteral(L,"");
    lua_rawseti(L,-2,1);
    lua_pushvalue(L,(3 + lc_nextra));
    lua_gettable(L,(2 + lc_nextra));
    lua_pushnumber(L,1);
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_rawseti(L,-2,2);
    lua_pushliteral(L,"");
    lua_rawseti(L,-2,3);
    lua_rawseti(L,-2,2);
    lua_createtable(L,3,0);
    lua_pushvalue(L,(3 + lc_nextra));
    lua_gettable(L,(2 + lc_nextra));
    lua_pushnumber(L,1);
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_rawseti(L,-2,1);
    lua_pushliteral(L,"");
    lua_rawseti(L,-2,2);
    lua_pushvalue(L,(3 + lc_nextra));
    lua_gettable(L,(2 + lc_nextra));
    lua_pushnumber(L,1);
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_rawseti(L,-2,3);
    lua_rawseti(L,-2,3);
    lua_rawset(L,-3);
    lua_call(L,1,0);
    assert(lua_gettop(L) - lc_nextra == 3);
    
    /* internal: stack cleanup on scope exit */
    lua_pop(L,1);
    lc1_var += lc3_step;
  }
  lua_settop(L,(lc5 + lc_nextra));
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- Paper (2x3 string = 4 paper)
   * minetest.register_craft({
   * 	output = "default:paper 4",
   * 	recipe = {
   * 		{"farming:string", "farming:string"},
   * 		{"farming:string", "farming:string"},
   * 		{"farming:string", "farming:string"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"default:paper 4");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"farming:string");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"farming:string");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,1);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"farming:string");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"farming:string");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,2);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"farming:string");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"farming:string");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- Palm Wax
   * minetest.register_craftitem("ethereal:palm_wax", {
   * 	description = S("Palm Wax"),
   * 	inventory_image = "palm_wax.png",
   * 	wield_image = "palm_wax.png",
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craftitem");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:palm_wax");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Palm Wax");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"palm_wax.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"palm_wax.png");
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* minetest.register_craft({
   * 	type = "cooking",
   * 	cooktime = 10,
   * 	output = "ethereal:palm_wax",
   * 	recipe = "ethereal:palmleaves"
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,4);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"cooking");
  lua_rawset(L,-3);
  lua_pushliteral(L,"cooktime");
  lua_pushnumber(L,10);
  lua_rawset(L,-3);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:palm_wax");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_pushliteral(L,"ethereal:palmleaves");
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- Candle from Wax and String/Cotton
   * minetest.register_node("ethereal:candle", {
   * 	description = S("Candle"),
   * 	drawtype = "plantlike",
   * 	inventory_image = "candle_static.png",
   * 	wield_image = "candle_static.png",
   * 	tiles = {
   * 		{
   * 			name = "candle.png",
   * 			animation={
   * 				type="vertical_frames",
   * 				aspect_w = 32,
   * 				aspect_h = 32,
   * 				length = 1.0
   * 			}
   * 		},
   * 	},	
   * 	paramtype = "light",
   * 	light_source = 11,
   * 	sunlight_propagates = true,
   * 	walkable = false,
   * 	groups = {dig_immediate = 3, attached_node = 1},
   * 	sounds = default.node_sound_defaults(),
   * 	selection_box = {
   * 		type = "fixed",
   * 		fixed = { -0.15, -0.5, -0.15, 0.15, 0.2, 0.15 }
   * 	},
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_node");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:candle");
  lua_createtable(L,0,12);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Candle");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"drawtype");
  lua_pushliteral(L,"plantlike");
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"candle_static.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"candle_static.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"tiles");
  lua_createtable(L,1,0);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"name");
  lua_pushliteral(L,"candle.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"animation");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"vertical_frames");
  lua_rawset(L,-3);
  lua_pushliteral(L,"aspect_w");
  lua_pushnumber(L,32);
  lua_rawset(L,-3);
  lua_pushliteral(L,"aspect_h");
  lua_pushnumber(L,32);
  lua_rawset(L,-3);
  lua_pushliteral(L,"length");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"paramtype");
  lua_pushliteral(L,"light");
  lua_rawset(L,-3);
  lua_pushliteral(L,"light_source");
  lua_pushnumber(L,11);
  lua_rawset(L,-3);
  lua_pushliteral(L,"sunlight_propagates");
  lua_pushboolean(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"walkable");
  lua_pushboolean(L,0);
  lua_rawset(L,-3);
  lua_pushliteral(L,"groups");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"dig_immediate");
  lua_pushnumber(L,3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"attached_node");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"sounds");
  lua_getfield(L,LUA_ENVIRONINDEX,"default");
  lua_pushliteral(L,"node_sound_defaults");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_call(L,0,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"selection_box");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"fixed");
  lua_rawset(L,-3);
  lua_pushliteral(L,"fixed");
  lua_createtable(L,6,0);
  lua_pushnumber(L,-0.15);
  lua_rawseti(L,-2,1);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,-0.15);
  lua_rawseti(L,-2,3);
  lua_pushnumber(L,0.15);
  lua_rawseti(L,-2,4);
  lua_pushnumber(L,0.2);
  lua_rawseti(L,-2,5);
  lua_pushnumber(L,0.15);
  lua_rawseti(L,-2,6);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* minetest.register_craft({
   * 	output = "ethereal:candle 2",
   * 	recipe = {
   * 		{"farming:cotton"},
   * 		{"ethereal:palm_wax"},
   * 		{"ethereal:palm_wax"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:candle 2");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"farming:cotton");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,1);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"ethereal:palm_wax");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,2);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"ethereal:palm_wax");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- Wooden Bowl
   * minetest.register_craftitem("ethereal:bowl", {
   * 	description = S("Bowl"),
   * 	inventory_image = "bowl.png",
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craftitem");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:bowl");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Bowl");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"bowl.png");
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* minetest.register_craft({
   * 	output = "ethereal:bowl",
   * 	recipe = {
   * 		{"group:wood", "", "group:wood"},
   * 		{"", "group:wood", ""},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:bowl");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,2,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"group:wood");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"group:wood");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"group:wood");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,2);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- stone Ladder
   * minetest.register_node("ethereal:stone_ladder", {
   * 	description = S("Stone Ladder"),
   * 	drawtype = "signlike",
   * 	tiles = {"stone_ladder.png"},
   * 	inventory_image = "stone_ladder.png",
   * 	wield_image = "stone_ladder.png",
   * 	paramtype = "light",
   * 	sunlight_propagates = true,
   * 	paramtype2 = "wallmounted",
   * 	walkable = false,
   * 	climbable = true,
   * 	is_ground_content = false,
   * 	selection_box = {
   * 		type = "wallmounted",
   * 	},
   * 	groups = {cracky = 3, oddly_breakable_by_hand = 1},
   * 	legacy_wallmounted = true,
   * 	sounds = default.node_sound_stone_defaults(),
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_node");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:stone_ladder");
  lua_createtable(L,0,15);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Stone Ladder");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"drawtype");
  lua_pushliteral(L,"signlike");
  lua_rawset(L,-3);
  lua_pushliteral(L,"tiles");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"stone_ladder.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"stone_ladder.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"stone_ladder.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"paramtype");
  lua_pushliteral(L,"light");
  lua_rawset(L,-3);
  lua_pushliteral(L,"sunlight_propagates");
  lua_pushboolean(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"paramtype2");
  lua_pushliteral(L,"wallmounted");
  lua_rawset(L,-3);
  lua_pushliteral(L,"walkable");
  lua_pushboolean(L,0);
  lua_rawset(L,-3);
  lua_pushliteral(L,"climbable");
  lua_pushboolean(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"is_ground_content");
  lua_pushboolean(L,0);
  lua_rawset(L,-3);
  lua_pushliteral(L,"selection_box");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"wallmounted");
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"groups");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"cracky");
  lua_pushnumber(L,3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"oddly_breakable_by_hand");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"legacy_wallmounted");
  lua_pushboolean(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"sounds");
  lua_getfield(L,LUA_ENVIRONINDEX,"default");
  lua_pushliteral(L,"node_sound_stone_defaults");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_call(L,0,1);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* minetest.register_craft({
   * 	output = "ethereal:stone_ladder 4",
   * 	recipe = {
   * 		{"default:cobble", "", "default:cobble"},
   * 		{"default:cobble", "default:cobble", "default:cobble"},
   * 		{"default:cobble", "", "default:cobble"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:stone_ladder 4");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:cobble");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"default:cobble");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:cobble");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:cobble");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"default:cobble");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,2);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:cobble");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"default:cobble");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- Paper Wall
   * minetest.register_node("ethereal:paper_wall", {
   * 	drawtype = "nodebox",
   * 	description = S("Paper Wall"),
   * 	tiles = {"paper_wall.png"},
   * 	inventory_image_image = "paper_wall.png",
   * 	wield_image = "paper_wall.png",
   * 	paramtype = "light",
   * 	groups = {snappy = 3},
   * 	sounds = default.node_sound_wood_defaults(),
   * 	walkable = true,
   * 	is_ground_content = false,
   * 	sunlight_propagates = true,
   * 	paramtype2 = "facedir",
   * 	selection_box = {
   * 		type = "fixed",
   * 		fixed = { -0.5, -0.5, 5/11, 0.5, 0.5, 8/16 }
   * 	},
   * 	node_box = {
   * 		type = "fixed",
   * 		fixed = {
   * 			{ -0.5, -0.5, 5/11, 0.5, 0.5, 8/16 }
   * 		}
   * 	},
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_node");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:paper_wall");
  lua_createtable(L,0,14);
  lua_pushliteral(L,"drawtype");
  lua_pushliteral(L,"nodebox");
  lua_rawset(L,-3);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Paper Wall");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"tiles");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"paper_wall.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image_image");
  lua_pushliteral(L,"paper_wall.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"paper_wall.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"paramtype");
  lua_pushliteral(L,"light");
  lua_rawset(L,-3);
  lua_pushliteral(L,"groups");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"snappy");
  lua_pushnumber(L,3);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"sounds");
  lua_getfield(L,LUA_ENVIRONINDEX,"default");
  lua_pushliteral(L,"node_sound_wood_defaults");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_call(L,0,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"walkable");
  lua_pushboolean(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"is_ground_content");
  lua_pushboolean(L,0);
  lua_rawset(L,-3);
  lua_pushliteral(L,"sunlight_propagates");
  lua_pushboolean(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"paramtype2");
  lua_pushliteral(L,"facedir");
  lua_rawset(L,-3);
  lua_pushliteral(L,"selection_box");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"fixed");
  lua_rawset(L,-3);
  lua_pushliteral(L,"fixed");
  lua_createtable(L,6,0);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,1);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,0.45454545454545);
  lua_rawseti(L,-2,3);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,4);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,5);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,6);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"node_box");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"fixed");
  lua_rawset(L,-3);
  lua_pushliteral(L,"fixed");
  lua_createtable(L,1,0);
  lua_createtable(L,6,0);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,1);
  lua_pushnumber(L,-0.5);
  lua_rawseti(L,-2,2);
  lua_pushnumber(L,0.45454545454545);
  lua_rawseti(L,-2,3);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,4);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,5);
  lua_pushnumber(L,0.5);
  lua_rawseti(L,-2,6);
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* minetest.register_craft({
   * 	output = "ethereal:paper_wall",
   * 	recipe = {
   * 		{"default:stick", "default:paper", "default:stick"},
   * 		{"default:stick", "default:paper", "default:stick"},
   * 		{"default:stick", "default:paper", "default:stick"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:paper_wall");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:stick");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:paper");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"default:stick");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:stick");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:paper");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"default:stick");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,2);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:stick");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:paper");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"default:stick");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- Glostone (A little bit of light decoration)
   * minetest.register_node("ethereal:glostone", {
   * 	description = S("Glo Stone"),
   * 	tiles = {"glostone.png"},
   * 	groups = {cracky = 3},
   * 	light_source = 13,
   * 	drop = "ethereal:glostone",
   * 	sounds = default.node_sound_stone_defaults(),
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_node");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:glostone");
  lua_createtable(L,0,6);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Glo Stone");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"tiles");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"glostone.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"groups");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"cracky");
  lua_pushnumber(L,3);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"light_source");
  lua_pushnumber(L,13);
  lua_rawset(L,-3);
  lua_pushliteral(L,"drop");
  lua_pushliteral(L,"ethereal:glostone");
  lua_rawset(L,-3);
  lua_pushliteral(L,"sounds");
  lua_getfield(L,LUA_ENVIRONINDEX,"default");
  lua_pushliteral(L,"node_sound_stone_defaults");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_call(L,0,1);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* minetest.register_craft({
   * 	output = "ethereal:glostone",
   * 	recipe = {
   * 		{"default:torch", "default:stone", "dye:yellow"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:glostone");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,1,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:torch");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:stone");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"dye:yellow");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- Charcoal Lump
   * minetest.register_craftitem("ethereal:charcoal_lump", {
   * 	description = S("Lump of Charcoal"),
   * 	inventory_image = "charcoal_lump.png",
   * 	wield_image = "charcoal_lump.png",
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craftitem");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:charcoal_lump");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Lump of Charcoal");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"charcoal_lump.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"charcoal_lump.png");
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* minetest.register_craft({
   * 	output = "ethereal:charcoal_lump 2",
   * 	recipe = {
   * 		{"ethereal:scorched_tree"}
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:charcoal_lump 2");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,1,0);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"ethereal:scorched_tree");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* minetest.register_craft({
   * 	output = "ethereal:charcoal_lump 2",
   * 	type = "cooking",
   * 	recipe = "group:tree",
   * 	cooktime = 4
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,4);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:charcoal_lump 2");
  lua_rawset(L,-3);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"cooking");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_pushliteral(L,"group:tree");
  lua_rawset(L,-3);
  lua_pushliteral(L,"cooktime");
  lua_pushnumber(L,4);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* minetest.register_craft({
   * 	type = "fuel",
   * 	recipe = "ethereal:charcoal_lump",
   * 	burntime = 10,
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,3);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"fuel");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_pushliteral(L,"ethereal:charcoal_lump");
  lua_rawset(L,-3);
  lua_pushliteral(L,"burntime");
  lua_pushnumber(L,10);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- Make Torch from Charcoal Lump
   * minetest.register_craft({
   * 	output = "default:torch 4",
   * 	recipe = {
   * 		{"ethereal:charcoal_lump"},
   * 		{"default:stick"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"default:torch 4");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,2,0);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"ethereal:charcoal_lump");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,1);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"default:stick");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,2);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- Staff of Light (by Xanthin)
   * minetest.register_tool("ethereal:light_staff", {
   * 	description = S("Staff of Light"),
   * 	inventory_image = "light_staff.png",
   * 	wield_image = "light_staff.png",
   * 	stack_max = 1,
   * 	on_use = function(itemstack, user, pointed_thing)
   * 
   * 		if pointed_thing.type ~= "node" then
   * 			return
   * 		end
   * 
   * 		local pos = pointed_thing.under
   * 		local pname = user:get_player_name()
   * 
   * 		if minetest.is_protected(pos, pname) then
   * 			minetest.record_protection_violation(pos, pname)
   * 			return
   * 		end
   * 
   * 		local node = minetest.get_node(pos).name
   * 
   * 		if node == "default:stone"
   * 		or node == "default:desert_stone" then
   * 
   * 			minetest.swap_node(pos, {name = "ethereal:glostone"})
   * 
   * 			if not minetest.setting_getbool("creative_mode") then
   * 				itemstack:add_wear(65535 / 149) -- 150 uses
   * 			end
   * 
   * 			return itemstack
   * 		end
   * 
   * 	end,
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_tool");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:light_staff");
  lua_createtable(L,0,5);
  lua_pushliteral(L,"description");
  lua_pushvalue(L,(1 + lc_nextra));
  lua_pushliteral(L,"Staff of Light");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"light_staff.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"light_staff.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"stack_max");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"on_use");
  lua_pushcfunction(L,lcf17);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* minetest.register_craft({
   * 	output = "ethereal:light_staff",
   * 	recipe = {
   * 		{"ethereal:illumishroom", "default:mese_crystal", "ethereal:illumishroom"},
   * 		{"ethereal:illumishroom2", "default:steel_ingot", "ethereal:illumishroom2"},
   * 		{"ethereal:illumishroom3", "default:steel_ingot", "ethereal:illumishroom3"}
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:light_staff");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:illumishroom");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:mese_crystal");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:illumishroom");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:illumishroom2");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:steel_ingot");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:illumishroom2");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,2);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:illumishroom3");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:steel_ingot");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:illumishroom3");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  return 0;
}


/* from lua.c */
static int traceback (lua_State *L) {
  if (!lua_isstring(L, 1))  /* 'message' not a string? */
    return 1;  /* keep it intact */
  lua_getfield(L, LUA_GLOBALSINDEX, "debug");
  if (!lua_istable(L, -1)) {
    lua_pop(L, 1);
    return 1;
  }
  lua_getfield(L, -1, "traceback");
  if (!lua_isfunction(L, -1)) {
    lua_pop(L, 2);
    return 1;
  }
  lua_pushvalue(L, 1);  /* pass error message */
  lua_pushinteger(L, 2);  /* skip this function and traceback */
  lua_call(L, 2, 1);  /* call debug.traceback */
  return 1;
}


static void lc_l_message (const char *pname, const char *msg) {
  if (pname) fprintf(stderr, "%s: ", pname);
  fprintf(stderr, "%s\n", msg);
  fflush(stderr);
}

static int lc_report (lua_State *L, int status) {
  if (status && !lua_isnil(L, -1)) {
    const char *msg = lua_tostring(L, -1);
    if (msg == NULL) msg = "(error object is not a string)";
    /*FIX-IMROVE:progname*/
    lc_l_message("lua", msg);
    lua_pop(L, 1);
  }
  return status;
}

static int lc_docall (lua_State *L, int narg, int clear) {
  int status;
  int base = lua_gettop(L) - narg;  /* function index */
  lua_pushcfunction(L, traceback);  /* push traceback function */
  lua_insert(L, base);  /* put it under chunk and args */
  /*FIX? signal(SIGINT, laction); */
  status = lua_pcall(L, narg, (clear ? 0 : LUA_MULTRET), base);
  /*FIX? signal(SIGINT, SIG_DFL); */
  lua_remove(L, base);  /* remove traceback function */
  /* force a complete garbage collection in case of errors */
  if (status != 0) lua_gc(L, LUA_GCCOLLECT, 0);
  return status;
}

static int lc_dofile (lua_State *L, const char *name) {
  int status = luaL_loadfile(L, name) || lc_docall(L, 0, 1);
  return lc_report(L, status);
}

static int lc_dostring (lua_State *L, const char *s, const char *name) {
  int status = luaL_loadbuffer(L, s, strlen(s), name) || lc_docall(L, 0, 1);
  return lc_report(L, status);
}

static int lc_handle_luainit (lua_State *L) {
  const char *init = getenv(LUA_INIT);
  if (init == NULL) return 0;  /* status OK */
  else if (init[0] == '@')
    return lc_dofile(L, init+1);
  else
    return lc_dostring(L, init, "=" LUA_INIT);
}


typedef struct {
  int c;
  const char ** v;
} lc_args_t;


/* create global arg table */
static void lc_createarg(lua_State * L, const lc_args_t * const args) {
  int i;
  lua_newtable(L);
  for (i=0; i < args->c; i++) {
    lua_pushstring(L, args->v[i]);
    lua_rawseti(L, -2, i);
  }
  lua_setglobal(L, "arg");
}


int lc_pmain_mod_ethereal_extra(lua_State * L) {
  luaL_openlibs(L);

  lua_pushcfunction(L, traceback);

  const int status1 = lc_handle_luainit(L);
  if (status1 != 0) return 0;

  /* note: IMPROVE: closure not always needed here */
  lua_newtable(L); /* closure table */
  lua_pushcclosure(L, lcf_main, 1);

  int status2 = lua_pcall(L, 0, 0, -2);
  if (status2 != 0) {
    const char * msg = lua_tostring(L,-1);
    if (msg == NULL) msg = "(error object is not a string)";
    fputs(msg, stderr);
  }
  return 0;
}


