/* WARNING: This file was automatically generated by lua2c. */

#ifdef __cplusplus
extern "C" {
#endif
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#ifdef __cplusplus
}
#endif
#include <stdio.h>
#include <stdlib.h>


#include <string.h>


/* pushes new closure table onto the stack, using closure table at
 * given index as its parent */
static void lc_newclosuretable(lua_State * L, int idx) {

  lua_newtable(L);
  lua_pushvalue(L,idx);
  lua_rawseti(L,-2,0);


}

#include <assert.h>

/* gets upvalue with ID varid by consulting upvalue table at index
 * tidx for the upvalue table at given nesting level. */
static void lc_getupvalue(lua_State * L, int tidx, int level, int varid) {
  if (level == 0) {
    lua_rawgeti(L,tidx,varid);
  }
  else {
    lua_pushvalue(L,tidx);
    while (--level >= 0) {
      lua_rawgeti(L,tidx,0); /* 0 links to parent table */
      lua_remove(L,-2);
      tidx = -1;
    }
    lua_rawgeti(L,-1,varid);
    lua_remove(L,-2);
  }
}


/* function (itemstack, user, pointed_thing) */
static int lcf18 (lua_State * L) {
  enum { lc_nformalargs = 3 };
  lua_settop(L,3);
  
  /* if pointed_thing.type ~= "node" then */
  enum { lc5 = 3 };
  lua_pushliteral(L,"type");
  lua_gettable(L,3);
  lua_pushliteral(L,"node");
  const int lc6 = lua_equal(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc6);
  lua_pushboolean(L,!(lua_toboolean(L,-1)));
  lua_remove(L,-2);
  const int lc7 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc7) {
    
    /* return */
    return 0;
    assert(lua_gettop(L) == 3);
  }
  lua_settop(L,lc5);
  assert(lua_gettop(L) == 3);
  
  /* local node = minetest.get_node(pointed_thing.under).name */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"get_node");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"under");
  lua_gettable(L,3);
  lua_call(L,1,1);
  lua_pushliteral(L,"name");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  assert(lua_gettop(L) == 4);
  
  /* if (node == "default:water_source"
   * 		or node == "default:river_water_source")
   * 		and math.random(1, 100) < 5 then */
  enum { lc8 = 4 };
  lua_pushvalue(L,4);
  lua_pushliteral(L,"default:water_source");
  const int lc9 = lua_equal(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc9);
  if (!(lua_toboolean(L,-1))) {
    lua_pop(L,1);
    lua_pushvalue(L,4);
    lua_pushliteral(L,"default:river_water_source");
    const int lc10 = lua_equal(L,-2,-1);
    lua_pop(L,2);
    lua_pushboolean(L,lc10);
  }
  if (lua_toboolean(L,-1)) {
    lua_pop(L,1);
    lua_getfield(L,LUA_ENVIRONINDEX,"math");
    lua_pushliteral(L,"random");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,1);
    lua_pushnumber(L,100);
    lua_call(L,2,1);
    lua_pushnumber(L,5);
    const int lc11 = lua_lessthan(L,-2,-1);
    lua_pop(L,2);
    lua_pushboolean(L,lc11);
  }
  const int lc12 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc12) {
    
    /* local type = fish[math.random(1, #fish)][1] */
    lc_getupvalue(L,lua_upvalueindex(1),0,2);
    lua_getfield(L,LUA_ENVIRONINDEX,"math");
    lua_pushliteral(L,"random");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,1);
    lc_getupvalue(L,lua_upvalueindex(1),0,2);
    const double lc13 = lua_objlen(L,-1);
    lua_pop(L,1);
    lua_pushnumber(L,lc13);
    lua_call(L,2,1);
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,1);
    lua_gettable(L,-2);
    lua_remove(L,-2);
    assert(lua_gettop(L) == 5);
    
    /* local inv = user:get_inventory() */
    lua_pushvalue(L,2);
    lua_pushliteral(L,"get_inventory");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_call(L,1,1);
    assert(lua_gettop(L) == 6);
    
    /* if inv:room_for_item("main", {name = type}) then */
    enum { lc14 = 6 };
    lua_pushvalue(L,6);
    lua_pushliteral(L,"room_for_item");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_pushliteral(L,"main");
    lua_createtable(L,0,1);
    lua_pushliteral(L,"name");
    lua_pushvalue(L,5);
    lua_rawset(L,-3);
    lua_call(L,3,1);
    const int lc15 = lua_toboolean(L,-1);
    lua_pop(L,1);
    if (lc15) {
      
      /* inv:add_item("main", {name = type}) */
      lua_pushvalue(L,6);
      lua_pushliteral(L,"add_item");
      lua_gettable(L,-2);
      lua_insert(L,-2);
      lua_pushliteral(L,"main");
      lua_createtable(L,0,1);
      lua_pushliteral(L,"name");
      lua_pushvalue(L,5);
      lua_rawset(L,-3);
      lua_call(L,3,0);
      assert(lua_gettop(L) == 6);
      
      /* return ItemStack("ethereal:fishing_rod") */
      const int lc16 = lua_gettop(L);
      lua_getfield(L,LUA_ENVIRONINDEX,"ItemStack");
      lua_pushliteral(L,"ethereal:fishing_rod");
      lua_call(L,1,LUA_MULTRET);
      return (lua_gettop(L) - lc16);
      assert(lua_gettop(L) == 6);
    }
    else {
      
      /* else
       * minetest.chat_send_player(user:get_player_name(),
       * 					S("Inventory full, Fish Got Away!")) */
      lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
      lua_pushliteral(L,"chat_send_player");
      lua_gettable(L,-2);
      lua_remove(L,-2);
      const int lc17 = lua_gettop(L);
      lua_pushvalue(L,2);
      lua_pushliteral(L,"get_player_name");
      lua_gettable(L,-2);
      lua_insert(L,-2);
      lua_call(L,1,1);
      lc_getupvalue(L,lua_upvalueindex(1),1,1);
      lua_pushliteral(L,"Inventory full, Fish Got Away!");
      lua_call(L,1,LUA_MULTRET);
      lua_call(L,(lua_gettop(L) - lc17),0);
      assert(lua_gettop(L) == 6);
    }
    lua_settop(L,lc14);
    assert(lua_gettop(L) == 6);
  }
  lua_settop(L,lc8);
  assert(lua_gettop(L) == 4);
  return 0;
}


/* name: (main)
 * function(...) */
static int lcf_main (lua_State * L) {
  enum { lc_nformalargs = 0 };
  const int lc_nactualargs = lua_gettop(L);
  const int lc_nextra = (lc_nactualargs - lc_nformalargs);
  
  /* local S = ethereal.intllib */
  lc_newclosuretable(L,lua_upvalueindex(1));
  enum { lc1 = 1 };
  assert((lua_gettop(L) == (lc1 + lc_nextra)));
  lua_getfield(L,LUA_ENVIRONINDEX,"ethereal");
  lua_pushliteral(L,"intllib");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_rawseti(L,(lc1 + lc_nextra),1);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Raw Fish (Thanks to Altairas for her Fish image on DeviantArt)
   * minetest.register_craftitem("ethereal:fish_raw", {
   * 	description = S("Raw Fish"),
   * 	inventory_image = "fish_raw.png",
   * 	wield_image = "fish_raw.png",
   * 	on_use = minetest.item_eat(2),
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craftitem");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:fish_raw");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"description");
  lc_getupvalue(L,(lc1 + lc_nextra),0,1);
  lua_pushliteral(L,"Raw Fish");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"fish_raw.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"fish_raw.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"on_use");
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"item_eat");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,2);
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Cooked Fish
   * minetest.register_craftitem("ethereal:fish_cooked", {
   * 	description = S("Cooked Fish"),
   * 	inventory_image = "fish_cooked.png",
   * 	wield_image = "fish_cooked.png",
   * 	on_use = minetest.item_eat(5),
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craftitem");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:fish_cooked");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"description");
  lc_getupvalue(L,(lc1 + lc_nextra),0,1);
  lua_pushliteral(L,"Cooked Fish");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"fish_cooked.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"fish_cooked.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"on_use");
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"item_eat");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,5);
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* minetest.register_craft({
   * 	type = "cooking",
   * 	output = "ethereal:fish_cooked",
   * 	recipe = "ethereal:fish_raw",
   * 	cooktime = 2,
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,4);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"cooking");
  lua_rawset(L,-3);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:fish_cooked");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_pushliteral(L,"ethereal:fish_raw");
  lua_rawset(L,-3);
  lua_pushliteral(L,"cooktime");
  lua_pushnumber(L,2);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Sashimi (Thanks to Natalia Grosner for letting me use the sashimi image)
   * minetest.register_craftitem("ethereal:sashimi", {
   * 	description = S("Sashimi"),
   * 	inventory_image = "sashimi.png",
   * 	wield_image = "sashimi.png",
   * 	on_use = minetest.item_eat(4),
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craftitem");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:sashimi");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"description");
  lc_getupvalue(L,(lc1 + lc_nextra),0,1);
  lua_pushliteral(L,"Sashimi");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"sashimi.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"sashimi.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"on_use");
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"item_eat");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,4);
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* minetest.register_craft({
   * 	output = "ethereal:sashimi 2",
   * 	recipe = {
   * 		{'ethereal:seaweed','ethereal:fish_raw','ethereal:seaweed'},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:sashimi 2");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,1,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"ethereal:seaweed");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:fish_raw");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"ethereal:seaweed");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Worm
   * minetest.register_craftitem("ethereal:worm", {
   * 	description = S("Worm"),
   * 	inventory_image = "worm.png",
   * 	wield_image = "worm.png",
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craftitem");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:worm");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"description");
  lc_getupvalue(L,(lc1 + lc_nextra),0,1);
  lua_pushliteral(L,"Worm");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"worm.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"worm.png");
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Fishing Rod
   * minetest.register_craftitem("ethereal:fishing_rod", {
   * 	description = S("Fishing Rod"),
   * 	inventory_image = "fishing_rod.png",
   * 	wield_image = "fishing_rod.png",
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craftitem");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:fishing_rod");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"description");
  lc_getupvalue(L,(lc1 + lc_nextra),0,1);
  lua_pushliteral(L,"Fishing Rod");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"fishing_rod.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"fishing_rod.png");
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* minetest.register_craft({
   * 	output = "ethereal:fishing_rod",
   * 	recipe = {
   * 			{"","","default:stick"},
   * 			{"", "default:stick", "farming:string"},
   * 			{"default:stick", "", "farming:string"},
   * 		}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:fishing_rod");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,3,0);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"default:stick");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,1);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:stick");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"farming:string");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,2);
  lua_createtable(L,3,0);
  lua_pushliteral(L,"default:stick");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"");
  lua_rawseti(L,-2,2);
  lua_pushliteral(L,"farming:string");
  lua_rawseti(L,-2,3);
  lua_rawseti(L,-2,3);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- Sift through 2 Dirt Blocks to find Worm
   * minetest.register_craft({
   * 	output = "ethereal:worm",
   * 	recipe = {
   * 		{"default:dirt","default:dirt"},
   * 	}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:worm");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,1,0);
  lua_createtable(L,2,0);
  lua_pushliteral(L,"default:dirt");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"default:dirt");
  lua_rawseti(L,-2,2);
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 1);
  
  /* -- default ethereal fish
   * local fish = {
   * 	{"ethereal:fish_raw"},
   * } */
  lc_newclosuretable(L,(lc1 + lc_nextra));
  enum { lc2 = 2 };
  assert((lua_gettop(L) == (lc2 + lc_nextra)));
  lua_createtable(L,1,0);
  lua_createtable(L,1,0);
  lua_pushliteral(L,"ethereal:fish_raw");
  lua_rawseti(L,-2,1);
  lua_rawseti(L,-2,1);
  lua_rawseti(L,(lc2 + lc_nextra),2);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- xanadu server additional fish
   * if minetest.get_modpath("xanadu") then */
  enum { lc3 = 2 };
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"get_modpath");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"xanadu");
  lua_call(L,1,1);
  const int lc4 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc4) {
    
    /* fish[2] = {"mobs:clownfish_raw"} */
    lua_createtable(L,1,0);
    lua_pushliteral(L,"mobs:clownfish_raw");
    lua_rawseti(L,-2,1);
    lc_getupvalue(L,(lc2 + lc_nextra),0,2);
    lua_insert(L,-2);
    lua_pushnumber(L,2);
    lua_insert(L,-2);
    lua_settable(L,-3);
    lua_pop(L,1);
    assert(lua_gettop(L) - lc_nextra == 2);
    
    /* fish[3] = {"mobs:bluefish_raw"} */
    lua_createtable(L,1,0);
    lua_pushliteral(L,"mobs:bluefish_raw");
    lua_rawseti(L,-2,1);
    lc_getupvalue(L,(lc2 + lc_nextra),0,2);
    lua_insert(L,-2);
    lua_pushnumber(L,3);
    lua_insert(L,-2);
    lua_settable(L,-3);
    lua_pop(L,1);
    assert(lua_gettop(L) - lc_nextra == 2);
  }
  lua_settop(L,(lc3 + lc_nextra));
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* -- Fishing Rod (Baited)
   * minetest.register_craftitem("ethereal:fishing_rod_baited", {
   * 	description = S("Baited Fishing Rod"),
   * 	inventory_image = "fishing_rod_baited.png",
   * 	wield_image = "fishing_rod_wield.png",
   * 	stack_max = 1,
   * 	liquids_pointable = true,
   * 
   * 	on_use = function (itemstack, user, pointed_thing)
   * 
   * 		if pointed_thing.type ~= "node" then
   * 			return
   * 		end
   * 		
   * 		local node = minetest.get_node(pointed_thing.under).name
   * 
   * 		if (node == "default:water_source"
   * 		or node == "default:river_water_source")
   * 		and math.random(1, 100) < 5 then
   * 
   * 			local type = fish[math.random(1, #fish)][1]
   * 			local inv = user:get_inventory()
   * 
   * 			if inv:room_for_item("main", {name = type}) then
   * 
   * 				inv:add_item("main", {name = type})
   * 
   * 				return ItemStack("ethereal:fishing_rod")
   * 			else
   * 				minetest.chat_send_player(user:get_player_name(),
   * 					S("Inventory full, Fish Got Away!"))
   * 			end
   * 		end
   * 	end,
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craftitem");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"ethereal:fishing_rod_baited");
  lua_createtable(L,0,6);
  lua_pushliteral(L,"description");
  lc_getupvalue(L,(lc2 + lc_nextra),1,1);
  lua_pushliteral(L,"Baited Fishing Rod");
  lua_call(L,1,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"fishing_rod_baited.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"wield_image");
  lua_pushliteral(L,"fishing_rod_wield.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"stack_max");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"liquids_pointable");
  lua_pushboolean(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"on_use");
  lua_pushvalue(L,(lc2 + lc_nextra));
  lua_pushcclosure(L,lcf18,1);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  
  /* minetest.register_craft({
   * 	type = "shapeless",
   * 	output = "ethereal:fishing_rod_baited",
   * 	recipe = {"ethereal:fishing_rod", "ethereal:worm"},
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_craft");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,3);
  lua_pushliteral(L,"type");
  lua_pushliteral(L,"shapeless");
  lua_rawset(L,-3);
  lua_pushliteral(L,"output");
  lua_pushliteral(L,"ethereal:fishing_rod_baited");
  lua_rawset(L,-3);
  lua_pushliteral(L,"recipe");
  lua_createtable(L,2,0);
  lua_pushliteral(L,"ethereal:fishing_rod");
  lua_rawseti(L,-2,1);
  lua_pushliteral(L,"ethereal:worm");
  lua_rawseti(L,-2,2);
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 2);
  return 0;
}


/* from lua.c */
static int traceback (lua_State *L) {
  if (!lua_isstring(L, 1))  /* 'message' not a string? */
    return 1;  /* keep it intact */
  lua_getfield(L, LUA_GLOBALSINDEX, "debug");
  if (!lua_istable(L, -1)) {
    lua_pop(L, 1);
    return 1;
  }
  lua_getfield(L, -1, "traceback");
  if (!lua_isfunction(L, -1)) {
    lua_pop(L, 2);
    return 1;
  }
  lua_pushvalue(L, 1);  /* pass error message */
  lua_pushinteger(L, 2);  /* skip this function and traceback */
  lua_call(L, 2, 1);  /* call debug.traceback */
  return 1;
}


static void lc_l_message (const char *pname, const char *msg) {
  if (pname) fprintf(stderr, "%s: ", pname);
  fprintf(stderr, "%s\n", msg);
  fflush(stderr);
}

static int lc_report (lua_State *L, int status) {
  if (status && !lua_isnil(L, -1)) {
    const char *msg = lua_tostring(L, -1);
    if (msg == NULL) msg = "(error object is not a string)";
    /*FIX-IMROVE:progname*/
    lc_l_message("lua", msg);
    lua_pop(L, 1);
  }
  return status;
}

static int lc_docall (lua_State *L, int narg, int clear) {
  int status;
  int base = lua_gettop(L) - narg;  /* function index */
  lua_pushcfunction(L, traceback);  /* push traceback function */
  lua_insert(L, base);  /* put it under chunk and args */
  /*FIX? signal(SIGINT, laction); */
  status = lua_pcall(L, narg, (clear ? 0 : LUA_MULTRET), base);
  /*FIX? signal(SIGINT, SIG_DFL); */
  lua_remove(L, base);  /* remove traceback function */
  /* force a complete garbage collection in case of errors */
  if (status != 0) lua_gc(L, LUA_GCCOLLECT, 0);
  return status;
}

static int lc_dofile (lua_State *L, const char *name) {
  int status = luaL_loadfile(L, name) || lc_docall(L, 0, 1);
  return lc_report(L, status);
}

static int lc_dostring (lua_State *L, const char *s, const char *name) {
  int status = luaL_loadbuffer(L, s, strlen(s), name) || lc_docall(L, 0, 1);
  return lc_report(L, status);
}

static int lc_handle_luainit (lua_State *L) {
  const char *init = getenv(LUA_INIT);
  if (init == NULL) return 0;  /* status OK */
  else if (init[0] == '@')
    return lc_dofile(L, init+1);
  else
    return lc_dostring(L, init, "=" LUA_INIT);
}


typedef struct {
  int c;
  const char ** v;
} lc_args_t;


/* create global arg table */
static void lc_createarg(lua_State * L, const lc_args_t * const args) {
  int i;
  lua_newtable(L);
  for (i=0; i < args->c; i++) {
    lua_pushstring(L, args->v[i]);
    lua_rawseti(L, -2, i);
  }
  lua_setglobal(L, "arg");
}


int lc_pmain_mod_ethereal_fishing(lua_State * L) {
  luaL_openlibs(L);

  lua_pushcfunction(L, traceback);

  const int status1 = lc_handle_luainit(L);
  if (status1 != 0) return 0;

  /* note: IMPROVE: closure not always needed here */
  lua_newtable(L); /* closure table */
  lua_pushcclosure(L, lcf_main, 1);

  int status2 = lua_pcall(L, 0, 0, -2);
  if (status2 != 0) {
    const char * msg = lua_tostring(L,-1);
    if (msg == NULL) msg = "(error object is not a string)";
    fputs(msg, stderr);
  }
  return 0;
}


