/* WARNING: This file was automatically generated by lua2c. */

#ifdef __cplusplus
extern "C" {
#endif
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#ifdef __cplusplus
}
#endif
#include <stdio.h>
#include <stdlib.h>


#include <string.h>


#include <assert.h>

/* function(self, player) */
static int lcf1 (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* local pos = self.object:getpos() */
  lua_pushliteral(L,"object");
  lua_gettable(L,1);
  lua_pushliteral(L,"getpos");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 3);
  
  /* nssm:duck_explosion(pos) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"duck_explosion");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,3);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* function(self, player) */
static int lcf2 (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* local pos = self.object:getpos() */
  lua_pushliteral(L,"object");
  lua_gettable(L,1);
  lua_pushliteral(L,"getpos");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 3);
  
  /* nssm:duck_explosion(pos) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"duck_explosion");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,3);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* function(self, pos, node) */
static int lcf3 (lua_State * L) {
  enum { lc_nformalargs = 3 };
  lua_settop(L,3);
  
  /* nssm:duck_explosion(pos) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"duck_explosion");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,2);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* pushes new closure table onto the stack, using closure table at
 * given index as its parent */
static void lc_newclosuretable(lua_State * L, int idx) {

  lua_newtable(L);
  lua_pushvalue(L,idx);
  lua_rawseti(L,-2,0);


}

/* __add metamethod handler.
 * warning: assumes indices in range LUA_REGISTRYINDEX < x < 0 are relative. */
static void lc_add(lua_State * L, int idxa, int idxb) {
  if (lua_isnumber(L,idxa) && lua_isnumber(L,idxb)) {
    lua_pushnumber(L,lua_tonumber(L,idxa) + lua_tonumber(L,idxb));
  }
  else {
    if (luaL_getmetafield(L,idxa,"__add")||luaL_getmetafield(L,idxb,"__add")) {
      lua_pushvalue(L,idxa < 0 && idxa > LUA_REGISTRYINDEX ? idxa-1 : idxa);
      lua_pushvalue(L,idxb < 0 && idxb > LUA_REGISTRYINDEX ? idxb-2 : idxb);
      lua_call(L,2,1);
    }
    else {
      luaL_error(L, "attempt to perform arithmetic");
    }
  }
}


/* gets upvalue with ID varid by consulting upvalue table at index
 * tidx for the upvalue table at given nesting level. */
static void lc_getupvalue(lua_State * L, int tidx, int level, int varid) {
  if (level == 0) {
    lua_rawgeti(L,tidx,varid);
  }
  else {
    lua_pushvalue(L,tidx);
    while (--level >= 0) {
      lua_rawgeti(L,tidx,0); /* 0 links to parent table */
      lua_remove(L,-2);
      tidx = -1;
    }
    lua_rawgeti(L,-1,varid);
    lua_remove(L,-2);
  }
}


/* __sub metamethod handler.
 * warning: assumes indices in range LUA_REGISTRYINDEX < x < 0 are relative. */
static void lc_sub(lua_State * L, int idxa, int idxb) {
  if (lua_isnumber(L,idxa) && lua_isnumber(L,idxb)) {
    lua_pushnumber(L,lua_tonumber(L,idxa) - lua_tonumber(L,idxb));
  }
  else {
    if (luaL_getmetafield(L,idxa,"__sub")||luaL_getmetafield(L,idxb,"__sub")) {
      lua_pushvalue(L,idxa < 0 && idxa > LUA_REGISTRYINDEX ? idxa-1 : idxa);
      lua_pushvalue(L,idxb < 0 && idxb > LUA_REGISTRYINDEX ? idxb-2 : idxb);
      lua_call(L,2,1);
    }
    else {
      luaL_error(L, "attempt to perform arithmetic");
    }
  }
}


static void lc_setupvalue(lua_State * L, int tidx, int level, int varid) {
  if (level == 0) {
    lua_rawseti(L,tidx,varid);
  }
  else {
    lua_pushvalue(L,tidx);
    while(--level >= 0) {
      lua_rawgeti(L,tidx,0); /* 0 links to parent table */
      lua_remove(L,-2);
      tidx = -1;
    }
    lua_insert(L,-2);
    lua_rawseti(L,-2,varid);
    lua_pop(L,1);
  }
}


/* function() */
static int lcf9 (lua_State * L) {
  enum { lc_nformalargs = 0 };
  lua_settop(L,0);
  
  /* for dx = -2,2 do */
  lua_pushnumber(L,-2);
  lua_pushnumber(L,2);
  if (!((lua_isnumber(L,-2) && lua_isnumber(L,-1)))) {
    luaL_error(L,"'for' limit must be a number");
  }
  double lc5_var = lua_tonumber(L,-2);
  const double lc6_limit = lua_tonumber(L,-1);
  const double lc7_step = 1;
  lua_pop(L,2);
  enum { lc8 = 0 };
  while ((((lc7_step > 0) && (lc5_var <= lc6_limit)) || ((lc7_step <= 0) && (lc5_var >= lc6_limit)))) {
    
    /* internal: local dx at index 1 */
    lua_pushnumber(L,lc5_var);
    
    /* pos = {x = pos.x+dx, y=pos.y; z=pos.z+dx} */
    lua_createtable(L,0,3);
    lua_pushliteral(L,"x");
    lc_getupvalue(L,lua_upvalueindex(1),0,1);
    lua_pushliteral(L,"x");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lc_add(L,-1,1);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"y");
    lc_getupvalue(L,lua_upvalueindex(1),0,1);
    lua_pushliteral(L,"y");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"z");
    lc_getupvalue(L,lua_upvalueindex(1),0,1);
    lua_pushliteral(L,"z");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lc_add(L,-1,1);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lc_setupvalue(L,lua_upvalueindex(1),0,1);
    assert(lua_gettop(L) == 1);
    
    /* minetest.add_particlespawner({
     * 				amount = 100,
     * 				time = 0.2,
     * 				minpos = {x=pos.x-1, y=pos.y-1, z=pos.z-1},
     * 				maxpos = {x=pos.x+1, y=pos.y+4, z=pos.z+1},
     * 				minvel = {x=0, y=0, z=0},
     * 				maxvel = {x=1, y=5, z=1},
     * 				minacc = {x=-0.5,y=5,z=-0.5},
     * 				maxacc = {x=0.5,y=5,z=0.5},
     * 				minexptime = 1,
     * 				maxexptime = 3,
     * 				minsize = 2,
     * 				maxsize = 4,
     * 				collisiondetection = false,
     * 				vertical = false,
     * 				texture = "tnt_smoke.png",
     * 			}) */
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"add_particlespawner");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_createtable(L,0,15);
    lua_pushliteral(L,"amount");
    lua_pushnumber(L,100);
    lua_rawset(L,-3);
    lua_pushliteral(L,"time");
    lua_pushnumber(L,0.2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"minpos");
    lua_createtable(L,0,3);
    lua_pushliteral(L,"x");
    lc_getupvalue(L,lua_upvalueindex(1),0,1);
    lua_pushliteral(L,"x");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,1);
    lc_sub(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"y");
    lc_getupvalue(L,lua_upvalueindex(1),0,1);
    lua_pushliteral(L,"y");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,1);
    lc_sub(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"z");
    lc_getupvalue(L,lua_upvalueindex(1),0,1);
    lua_pushliteral(L,"z");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,1);
    lc_sub(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_rawset(L,-3);
    lua_pushliteral(L,"maxpos");
    lua_createtable(L,0,3);
    lua_pushliteral(L,"x");
    lc_getupvalue(L,lua_upvalueindex(1),0,1);
    lua_pushliteral(L,"x");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,1);
    lc_add(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"y");
    lc_getupvalue(L,lua_upvalueindex(1),0,1);
    lua_pushliteral(L,"y");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,4);
    lc_add(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"z");
    lc_getupvalue(L,lua_upvalueindex(1),0,1);
    lua_pushliteral(L,"z");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,1);
    lc_add(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_rawset(L,-3);
    lua_pushliteral(L,"minvel");
    lua_createtable(L,0,3);
    lua_pushliteral(L,"x");
    lua_pushnumber(L,0);
    lua_rawset(L,-3);
    lua_pushliteral(L,"y");
    lua_pushnumber(L,0);
    lua_rawset(L,-3);
    lua_pushliteral(L,"z");
    lua_pushnumber(L,0);
    lua_rawset(L,-3);
    lua_rawset(L,-3);
    lua_pushliteral(L,"maxvel");
    lua_createtable(L,0,3);
    lua_pushliteral(L,"x");
    lua_pushnumber(L,1);
    lua_rawset(L,-3);
    lua_pushliteral(L,"y");
    lua_pushnumber(L,5);
    lua_rawset(L,-3);
    lua_pushliteral(L,"z");
    lua_pushnumber(L,1);
    lua_rawset(L,-3);
    lua_rawset(L,-3);
    lua_pushliteral(L,"minacc");
    lua_createtable(L,0,3);
    lua_pushliteral(L,"x");
    lua_pushnumber(L,-0.5);
    lua_rawset(L,-3);
    lua_pushliteral(L,"y");
    lua_pushnumber(L,5);
    lua_rawset(L,-3);
    lua_pushliteral(L,"z");
    lua_pushnumber(L,-0.5);
    lua_rawset(L,-3);
    lua_rawset(L,-3);
    lua_pushliteral(L,"maxacc");
    lua_createtable(L,0,3);
    lua_pushliteral(L,"x");
    lua_pushnumber(L,0.5);
    lua_rawset(L,-3);
    lua_pushliteral(L,"y");
    lua_pushnumber(L,5);
    lua_rawset(L,-3);
    lua_pushliteral(L,"z");
    lua_pushnumber(L,0.5);
    lua_rawset(L,-3);
    lua_rawset(L,-3);
    lua_pushliteral(L,"minexptime");
    lua_pushnumber(L,1);
    lua_rawset(L,-3);
    lua_pushliteral(L,"maxexptime");
    lua_pushnumber(L,3);
    lua_rawset(L,-3);
    lua_pushliteral(L,"minsize");
    lua_pushnumber(L,2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"maxsize");
    lua_pushnumber(L,4);
    lua_rawset(L,-3);
    lua_pushliteral(L,"collisiondetection");
    lua_pushboolean(L,0);
    lua_rawset(L,-3);
    lua_pushliteral(L,"vertical");
    lua_pushboolean(L,0);
    lua_rawset(L,-3);
    lua_pushliteral(L,"texture");
    lua_pushliteral(L,"tnt_smoke.png");
    lua_rawset(L,-3);
    lua_call(L,1,0);
    assert(lua_gettop(L) == 1);
    
    /* minetest.add_entity(pos, "nssm:duck") */
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"add_entity");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lc_getupvalue(L,lua_upvalueindex(1),0,1);
    lua_pushliteral(L,"nssm:duck");
    lua_call(L,2,0);
    assert(lua_gettop(L) == 1);
    
    /* internal: stack cleanup on scope exit */
    lua_pop(L,1);
    lc5_var += lc7_step;
  }
  lua_settop(L,lc8);
  assert(lua_gettop(L) == 0);
  return 0;
}


/* name: nssm:duck_explosion
 * function(pos) */
static int lcf1_nssm_duck_explosion (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  lc_newclosuretable(L,lua_upvalueindex(1));
  enum { lc4 = 3 };
  assert((lua_gettop(L) == lc4));
  lua_pushvalue(L,2);
  lua_rawseti(L,-2,1);
  
  /* pos.y = pos.y+1 */
  lc_getupvalue(L,lc4,0,1);
  lua_pushliteral(L,"y");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,1);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lc_getupvalue(L,lc4,0,1);
  lua_insert(L,-2);
  lua_pushliteral(L,"y");
  lua_insert(L,-2);
  lua_settable(L,-3);
  lua_pop(L,1);
  assert(lua_gettop(L) == 3);
  
  /* minetest.add_particlespawner({
   * 		amount = 10,
   * 		time = 0.2,
   * 		minpos = {x=pos.x-1, y=pos.y-1, z=pos.z-1},
   * 		maxpos = {x=pos.x+1, y=pos.y+4, z=pos.z+1},
   * 		minvel = {x=0, y=0, z=0},
   * 		maxvel = {x=1, y=1, z=1},
   * 		minacc = {x=-0.5,y=5,z=-0.5},
   * 		maxacc = {x=0.5,y=5,z=0.5},
   * 		minexptime = 1,
   * 		maxexptime = 3,
   * 		minsize = 4,
   * 		maxsize = 6,
   * 		collisiondetection = false,
   * 		vertical = false,
   * 		texture = "duck_egg_fragments.png",
   * 	}) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"add_particlespawner");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_createtable(L,0,15);
  lua_pushliteral(L,"amount");
  lua_pushnumber(L,10);
  lua_rawset(L,-3);
  lua_pushliteral(L,"time");
  lua_pushnumber(L,0.2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"minpos");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"x");
  lc_getupvalue(L,lc4,0,1);
  lua_pushliteral(L,"x");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,1);
  lc_sub(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lc_getupvalue(L,lc4,0,1);
  lua_pushliteral(L,"y");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,1);
  lc_sub(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"z");
  lc_getupvalue(L,lc4,0,1);
  lua_pushliteral(L,"z");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,1);
  lc_sub(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"maxpos");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"x");
  lc_getupvalue(L,lc4,0,1);
  lua_pushliteral(L,"x");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,1);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lc_getupvalue(L,lc4,0,1);
  lua_pushliteral(L,"y");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,4);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"z");
  lc_getupvalue(L,lc4,0,1);
  lua_pushliteral(L,"z");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,1);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"minvel");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"x");
  lua_pushnumber(L,0);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushnumber(L,0);
  lua_rawset(L,-3);
  lua_pushliteral(L,"z");
  lua_pushnumber(L,0);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"maxvel");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"x");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"z");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"minacc");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"x");
  lua_pushnumber(L,-0.5);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushnumber(L,5);
  lua_rawset(L,-3);
  lua_pushliteral(L,"z");
  lua_pushnumber(L,-0.5);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"maxacc");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"x");
  lua_pushnumber(L,0.5);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushnumber(L,5);
  lua_rawset(L,-3);
  lua_pushliteral(L,"z");
  lua_pushnumber(L,0.5);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"minexptime");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"maxexptime");
  lua_pushnumber(L,3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"minsize");
  lua_pushnumber(L,4);
  lua_rawset(L,-3);
  lua_pushliteral(L,"maxsize");
  lua_pushnumber(L,6);
  lua_rawset(L,-3);
  lua_pushliteral(L,"collisiondetection");
  lua_pushboolean(L,0);
  lua_rawset(L,-3);
  lua_pushliteral(L,"vertical");
  lua_pushboolean(L,0);
  lua_rawset(L,-3);
  lua_pushliteral(L,"texture");
  lua_pushliteral(L,"duck_egg_fragments.png");
  lua_rawset(L,-3);
  lua_call(L,1,0);
  assert(lua_gettop(L) == 3);
  
  /* core.after(0.4, function()
   * 		for dx = -2,2 do
   * 			pos = {x = pos.x+dx, y=pos.y; z=pos.z+dx}
   * 			minetest.add_particlespawner({
   * 				amount = 100,
   * 				time = 0.2,
   * 				minpos = {x=pos.x-1, y=pos.y-1, z=pos.z-1},
   * 				maxpos = {x=pos.x+1, y=pos.y+4, z=pos.z+1},
   * 				minvel = {x=0, y=0, z=0},
   * 				maxvel = {x=1, y=5, z=1},
   * 				minacc = {x=-0.5,y=5,z=-0.5},
   * 				maxacc = {x=0.5,y=5,z=0.5},
   * 				minexptime = 1,
   * 				maxexptime = 3,
   * 				minsize = 2,
   * 				maxsize = 4,
   * 				collisiondetection = false,
   * 				vertical = false,
   * 				texture = "tnt_smoke.png",
   * 			})
   * 			minetest.add_entity(pos, "nssm:duck")
   * 		end
   * 	end) */
  lua_getfield(L,LUA_ENVIRONINDEX,"core");
  lua_pushliteral(L,"after");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,0.4);
  lua_pushvalue(L,lc4);
  lua_pushcclosure(L,lcf9,1);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* function(self, player) */
static int lcf10 (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* local pos = self.object:getpos() */
  lua_pushliteral(L,"object");
  lua_gettable(L,1);
  lua_pushliteral(L,"getpos");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 3);
  
  /* nssm:ice_explosion(pos) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"ice_explosion");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,3);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* function(self, player) */
static int lcf11 (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* local pos = self.object:getpos() */
  lua_pushliteral(L,"object");
  lua_gettable(L,1);
  lua_pushliteral(L,"getpos");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 3);
  
  /* nssm:ice_explosion(pos) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"ice_explosion");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,3);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* function(self, pos, node) */
static int lcf12 (lua_State * L) {
  enum { lc_nformalargs = 3 };
  lua_settop(L,3);
  
  /* nssm:ice_explosion(pos) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"ice_explosion");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,2);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* name: nssm:ice_explosion
 * function(pos) */
static int lcf1_nssm_ice_explosion (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* for i=pos.x-math.random(0, 1), pos.x+math.random(0, 1), 1 do */
  lua_pushliteral(L,"x");
  lua_gettable(L,2);
  lua_getfield(L,LUA_ENVIRONINDEX,"math");
  lua_pushliteral(L,"random");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,0);
  lua_pushnumber(L,1);
  lua_call(L,2,1);
  lc_sub(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"x");
  lua_gettable(L,2);
  lua_getfield(L,LUA_ENVIRONINDEX,"math");
  lua_pushliteral(L,"random");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,0);
  lua_pushnumber(L,1);
  lua_call(L,2,1);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,1);
  if (!(((lua_isnumber(L,-3) && lua_isnumber(L,-2)) && lua_isnumber(L,-1)))) {
    luaL_error(L,"'for' limit must be a number");
  }
  double lc13_var = lua_tonumber(L,-3);
  const double lc14_limit = lua_tonumber(L,-2);
  const double lc15_step = lua_tonumber(L,-1);
  lua_pop(L,3);
  enum { lc16 = 2 };
  while ((((lc15_step > 0) && (lc13_var <= lc14_limit)) || ((lc15_step <= 0) && (lc13_var >= lc14_limit)))) {
    
    /* internal: local i at index 3 */
    lua_pushnumber(L,lc13_var);
    
    /* for j=pos.y-1, pos.y+4, 1 do */
    lua_pushliteral(L,"y");
    lua_gettable(L,2);
    lua_pushnumber(L,1);
    lc_sub(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_pushliteral(L,"y");
    lua_gettable(L,2);
    lua_pushnumber(L,4);
    lc_add(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,1);
    if (!(((lua_isnumber(L,-3) && lua_isnumber(L,-2)) && lua_isnumber(L,-1)))) {
      luaL_error(L,"'for' limit must be a number");
    }
    double lc17_var = lua_tonumber(L,-3);
    const double lc18_limit = lua_tonumber(L,-2);
    const double lc19_step = lua_tonumber(L,-1);
    lua_pop(L,3);
    enum { lc20 = 3 };
    while ((((lc19_step > 0) && (lc17_var <= lc18_limit)) || ((lc19_step <= 0) && (lc17_var >= lc18_limit)))) {
      
      /* internal: local j at index 4 */
      lua_pushnumber(L,lc17_var);
      
      /* for k=pos.z-math.random(0, 1), pos.z+math.random(0, 1), 1 do */
      lua_pushliteral(L,"z");
      lua_gettable(L,2);
      lua_getfield(L,LUA_ENVIRONINDEX,"math");
      lua_pushliteral(L,"random");
      lua_gettable(L,-2);
      lua_remove(L,-2);
      lua_pushnumber(L,0);
      lua_pushnumber(L,1);
      lua_call(L,2,1);
      lc_sub(L,-2,-1);
      lua_remove(L,-2);
      lua_remove(L,-2);
      lua_pushliteral(L,"z");
      lua_gettable(L,2);
      lua_getfield(L,LUA_ENVIRONINDEX,"math");
      lua_pushliteral(L,"random");
      lua_gettable(L,-2);
      lua_remove(L,-2);
      lua_pushnumber(L,0);
      lua_pushnumber(L,1);
      lua_call(L,2,1);
      lc_add(L,-2,-1);
      lua_remove(L,-2);
      lua_remove(L,-2);
      lua_pushnumber(L,1);
      if (!(((lua_isnumber(L,-3) && lua_isnumber(L,-2)) && lua_isnumber(L,-1)))) {
        luaL_error(L,"'for' limit must be a number");
      }
      double lc21_var = lua_tonumber(L,-3);
      const double lc22_limit = lua_tonumber(L,-2);
      const double lc23_step = lua_tonumber(L,-1);
      lua_pop(L,3);
      enum { lc24 = 4 };
      while ((((lc23_step > 0) && (lc21_var <= lc22_limit)) || ((lc23_step <= 0) && (lc21_var >= lc22_limit)))) {
        
        /* internal: local k at index 5 */
        lua_pushnumber(L,lc21_var);
        
        /* minetest.set_node({x=i, y=j, z=k}, {name="default:ice"}) */
        lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
        lua_pushliteral(L,"set_node");
        lua_gettable(L,-2);
        lua_remove(L,-2);
        lua_createtable(L,0,3);
        lua_pushliteral(L,"x");
        lua_pushvalue(L,3);
        lua_rawset(L,-3);
        lua_pushliteral(L,"y");
        lua_pushvalue(L,4);
        lua_rawset(L,-3);
        lua_pushliteral(L,"z");
        lua_pushvalue(L,5);
        lua_rawset(L,-3);
        lua_createtable(L,0,1);
        lua_pushliteral(L,"name");
        lua_pushliteral(L,"default:ice");
        lua_rawset(L,-3);
        lua_call(L,2,0);
        assert(lua_gettop(L) == 5);
        
        /* internal: stack cleanup on scope exit */
        lua_pop(L,1);
        lc21_var += lc23_step;
      }
      lua_settop(L,lc24);
      assert(lua_gettop(L) == 4);
      
      /* internal: stack cleanup on scope exit */
      lua_pop(L,1);
      lc17_var += lc19_step;
    }
    lua_settop(L,lc20);
    assert(lua_gettop(L) == 3);
    
    /* internal: stack cleanup on scope exit */
    lua_pop(L,1);
    lc13_var += lc15_step;
  }
  lua_settop(L,lc16);
  assert(lua_gettop(L) == 2);
  return 0;
}


/* function(self, player) */
static int lcf25 (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* player:punch(self.object, 1.0, {
   * 			full_punch_interval = 1.0,
   * 			damage_groups = {fleshy = 2},
   * 		}, nil) */
  lua_pushvalue(L,2);
  lua_pushliteral(L,"punch");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushliteral(L,"object");
  lua_gettable(L,1);
  lua_pushnumber(L,1);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"full_punch_interval");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"damage_groups");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"fleshy");
  lua_pushnumber(L,2);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushnil(L);
  lua_call(L,5,0);
  assert(lua_gettop(L) == 2);
  return 0;
}


/* function(self, player) */
static int lcf26 (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* player:punch(self.object, 1.0, {
   * 			full_punch_interval = 1.0,
   * 			damage_groups = {fleshy = 2},
   * 		}, nil) */
  lua_pushvalue(L,2);
  lua_pushliteral(L,"punch");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushliteral(L,"object");
  lua_gettable(L,1);
  lua_pushnumber(L,1);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"full_punch_interval");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"damage_groups");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"fleshy");
  lua_pushnumber(L,2);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushnil(L);
  lua_call(L,5,0);
  assert(lua_gettop(L) == 2);
  return 0;
}


/* function(self, player) */
static int lcf27 (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* local p = player:getpos() */
  lua_pushvalue(L,2);
  lua_pushliteral(L,"getpos");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 3);
  
  /* nssm:explosion_web(p) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"explosion_web");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,3);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* function(self, player) */
static int lcf28 (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* player:punch(self.object, 1.0, {
   * 			full_punch_interval = 1.0,
   * 			damage_groups = {fleshy = 1},
   * 		}, nil) */
  lua_pushvalue(L,2);
  lua_pushliteral(L,"punch");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushliteral(L,"object");
  lua_gettable(L,1);
  lua_pushnumber(L,1);
  lua_createtable(L,0,2);
  lua_pushliteral(L,"full_punch_interval");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"damage_groups");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"fleshy");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushnil(L);
  lua_call(L,5,0);
  assert(lua_gettop(L) == 2);
  return 0;
}


/* function(self, pos, node) */
static int lcf29 (lua_State * L) {
  enum { lc_nformalargs = 3 };
  lua_settop(L,3);
  
  /* nssm:explosion_web(pos) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"explosion_web");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,2);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* name: nssm:explosion_web
 * function(pos) */
static int lcf1_nssm_explosion_web (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* if minetest.is_protected(pos, "") then */
  enum { lc30 = 2 };
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"is_protected");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushvalue(L,2);
  lua_pushliteral(L,"");
  lua_call(L,2,1);
  const int lc31 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc31) {
    
    /* return */
    return 0;
    assert(lua_gettop(L) == 2);
  }
  lua_settop(L,lc30);
  assert(lua_gettop(L) == 2);
  
  /* pos.y = nssm:round(pos.y) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"round");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushliteral(L,"y");
  lua_gettable(L,2);
  lua_call(L,2,1);
  lua_pushliteral(L,"y");
  lua_insert(L,-2);
  lua_settable(L,2);
  assert(lua_gettop(L) == 2);
  
  /* for i=pos.x-1, pos.x+1, 1 do */
  lua_pushliteral(L,"x");
  lua_gettable(L,2);
  lua_pushnumber(L,1);
  lc_sub(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"x");
  lua_gettable(L,2);
  lua_pushnumber(L,1);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,1);
  if (!(((lua_isnumber(L,-3) && lua_isnumber(L,-2)) && lua_isnumber(L,-1)))) {
    luaL_error(L,"'for' limit must be a number");
  }
  double lc32_var = lua_tonumber(L,-3);
  const double lc33_limit = lua_tonumber(L,-2);
  const double lc34_step = lua_tonumber(L,-1);
  lua_pop(L,3);
  enum { lc35 = 2 };
  while ((((lc34_step > 0) && (lc32_var <= lc33_limit)) || ((lc34_step <= 0) && (lc32_var >= lc33_limit)))) {
    
    /* internal: local i at index 3 */
    lua_pushnumber(L,lc32_var);
    
    /* for j=pos.y-3, pos.y, 1 do */
    lua_pushliteral(L,"y");
    lua_gettable(L,2);
    lua_pushnumber(L,3);
    lc_sub(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_pushliteral(L,"y");
    lua_gettable(L,2);
    lua_pushnumber(L,1);
    if (!(((lua_isnumber(L,-3) && lua_isnumber(L,-2)) && lua_isnumber(L,-1)))) {
      luaL_error(L,"'for' limit must be a number");
    }
    double lc36_var = lua_tonumber(L,-3);
    const double lc37_limit = lua_tonumber(L,-2);
    const double lc38_step = lua_tonumber(L,-1);
    lua_pop(L,3);
    enum { lc39 = 3 };
    while ((((lc38_step > 0) && (lc36_var <= lc37_limit)) || ((lc38_step <= 0) && (lc36_var >= lc37_limit)))) {
      
      /* internal: local j at index 4 */
      lua_pushnumber(L,lc36_var);
      
      /* for k=pos.z-1, pos.z+1, 1 do */
      lua_pushliteral(L,"z");
      lua_gettable(L,2);
      lua_pushnumber(L,1);
      lc_sub(L,-2,-1);
      lua_remove(L,-2);
      lua_remove(L,-2);
      lua_pushliteral(L,"z");
      lua_gettable(L,2);
      lua_pushnumber(L,1);
      lc_add(L,-2,-1);
      lua_remove(L,-2);
      lua_remove(L,-2);
      lua_pushnumber(L,1);
      if (!(((lua_isnumber(L,-3) && lua_isnumber(L,-2)) && lua_isnumber(L,-1)))) {
        luaL_error(L,"'for' limit must be a number");
      }
      double lc40_var = lua_tonumber(L,-3);
      const double lc41_limit = lua_tonumber(L,-2);
      const double lc42_step = lua_tonumber(L,-1);
      lua_pop(L,3);
      enum { lc43 = 4 };
      while ((((lc42_step > 0) && (lc40_var <= lc41_limit)) || ((lc42_step <= 0) && (lc40_var >= lc41_limit)))) {
        
        /* internal: local k at index 5 */
        lua_pushnumber(L,lc40_var);
        
        /* local p = {x=i,y=j,z=k} */
        lua_createtable(L,0,3);
        lua_pushliteral(L,"x");
        lua_pushvalue(L,3);
        lua_rawset(L,-3);
        lua_pushliteral(L,"y");
        lua_pushvalue(L,4);
        lua_rawset(L,-3);
        lua_pushliteral(L,"z");
        lua_pushvalue(L,5);
        lua_rawset(L,-3);
        assert(lua_gettop(L) == 6);
        
        /* local k = {x=i,y=j+1,z=k} */
        lua_createtable(L,0,3);
        lua_pushliteral(L,"x");
        lua_pushvalue(L,3);
        lua_rawset(L,-3);
        lua_pushliteral(L,"y");
        lua_pushnumber(L,1);
        lc_add(L,4,-1);
        lua_remove(L,-2);
        lua_rawset(L,-3);
        lua_pushliteral(L,"z");
        lua_pushvalue(L,5);
        lua_rawset(L,-3);
        assert(lua_gettop(L) == 7);
        
        /* local current = minetest.env:get_node(p).name */
        lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
        lua_pushliteral(L,"env");
        lua_gettable(L,-2);
        lua_remove(L,-2);
        lua_pushliteral(L,"get_node");
        lua_gettable(L,-2);
        lua_insert(L,-2);
        lua_pushvalue(L,6);
        lua_call(L,2,1);
        lua_pushliteral(L,"name");
        lua_gettable(L,-2);
        lua_remove(L,-2);
        assert(lua_gettop(L) == 8);
        
        /* local ontop  = minetest.env:get_node(k).name */
        lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
        lua_pushliteral(L,"env");
        lua_gettable(L,-2);
        lua_remove(L,-2);
        lua_pushliteral(L,"get_node");
        lua_gettable(L,-2);
        lua_insert(L,-2);
        lua_pushvalue(L,7);
        lua_call(L,2,1);
        lua_pushliteral(L,"name");
        lua_gettable(L,-2);
        lua_remove(L,-2);
        assert(lua_gettop(L) == 9);
        
        /* if 	(current ~= "air") and
         * 					(current ~= "nssm:web") and
         * 					(ontop == "air") and not
         * 					minetest.is_protected(p,"") and not
         * 					minetest.is_protected(k,"") then */
        enum { lc44 = 9 };
        lua_pushliteral(L,"air");
        const int lc45 = lua_equal(L,8,-1);
        lua_pop(L,1);
        lua_pushboolean(L,lc45);
        lua_pushboolean(L,!(lua_toboolean(L,-1)));
        lua_remove(L,-2);
        if (lua_toboolean(L,-1)) {
          lua_pop(L,1);
          lua_pushliteral(L,"nssm:web");
          const int lc46 = lua_equal(L,8,-1);
          lua_pop(L,1);
          lua_pushboolean(L,lc46);
          lua_pushboolean(L,!(lua_toboolean(L,-1)));
          lua_remove(L,-2);
        }
        if (lua_toboolean(L,-1)) {
          lua_pop(L,1);
          lua_pushvalue(L,9);
          lua_pushliteral(L,"air");
          const int lc47 = lua_equal(L,-2,-1);
          lua_pop(L,2);
          lua_pushboolean(L,lc47);
        }
        if (lua_toboolean(L,-1)) {
          lua_pop(L,1);
          lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
          lua_pushliteral(L,"is_protected");
          lua_gettable(L,-2);
          lua_remove(L,-2);
          lua_pushvalue(L,6);
          lua_pushliteral(L,"");
          lua_call(L,2,1);
          lua_pushboolean(L,!(lua_toboolean(L,-1)));
          lua_remove(L,-2);
        }
        if (lua_toboolean(L,-1)) {
          lua_pop(L,1);
          lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
          lua_pushliteral(L,"is_protected");
          lua_gettable(L,-2);
          lua_remove(L,-2);
          lua_pushvalue(L,7);
          lua_pushliteral(L,"");
          lua_call(L,2,1);
          lua_pushboolean(L,!(lua_toboolean(L,-1)));
          lua_remove(L,-2);
        }
        const int lc48 = lua_toboolean(L,-1);
        lua_pop(L,1);
        if (lc48) {
          
          /* minetest.set_node(k, {name="nssm:web"}) */
          lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
          lua_pushliteral(L,"set_node");
          lua_gettable(L,-2);
          lua_remove(L,-2);
          lua_pushvalue(L,7);
          lua_createtable(L,0,1);
          lua_pushliteral(L,"name");
          lua_pushliteral(L,"nssm:web");
          lua_rawset(L,-3);
          lua_call(L,2,0);
          assert(lua_gettop(L) == 9);
        }
        lua_settop(L,lc44);
        assert(lua_gettop(L) == 9);
        
        /* internal: stack cleanup on scope exit */
        lua_pop(L,5);
        lc40_var += lc42_step;
      }
      lua_settop(L,lc43);
      assert(lua_gettop(L) == 4);
      
      /* internal: stack cleanup on scope exit */
      lua_pop(L,1);
      lc36_var += lc38_step;
    }
    lua_settop(L,lc39);
    assert(lua_gettop(L) == 3);
    
    /* internal: stack cleanup on scope exit */
    lua_pop(L,1);
    lc32_var += lc34_step;
  }
  lua_settop(L,lc35);
  assert(lua_gettop(L) == 2);
  return 0;
}


/* function(self, player) */
static int lcf49 (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  return 0;
}


/* function(self, dtime) */
static int lcf67 (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* local pos = self.object:getpos() */
  lua_pushliteral(L,"object");
  lua_gettable(L,1);
  lua_pushliteral(L,"getpos");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 3);
  
  /* local n = minetest.env:get_node(pos).name */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"env");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"get_node");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,3);
  lua_call(L,2,1);
  lua_pushliteral(L,"name");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  assert(lua_gettop(L) == 4);
  
  /* if self.timer == 0 then */
  enum { lc50 = 4 };
  lua_pushliteral(L,"timer");
  lua_gettable(L,1);
  lua_pushnumber(L,0);
  const int lc51 = lua_equal(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc51);
  const int lc52 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc52) {
    
    /* self.timer = os.time() */
    lua_getfield(L,LUA_ENVIRONINDEX,"os");
    lua_pushliteral(L,"time");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_call(L,0,1);
    lua_pushliteral(L,"timer");
    lua_insert(L,-2);
    lua_settable(L,1);
    assert(lua_gettop(L) == 4);
  }
  lua_settop(L,lc50);
  assert(lua_gettop(L) == 4);
  
  /* if os.time() - self.timer > 5 or minetest.is_protected(pos, "") or ((n~="air") and (n~="fire:basic_flame")) then */
  enum { lc53 = 4 };
  lua_pushnumber(L,5);
  lua_getfield(L,LUA_ENVIRONINDEX,"os");
  lua_pushliteral(L,"time");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_call(L,0,1);
  lua_pushliteral(L,"timer");
  lua_gettable(L,1);
  lc_sub(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  const int lc54 = lua_lessthan(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc54);
  if (!(lua_toboolean(L,-1))) {
    lua_pop(L,1);
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"is_protected");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushvalue(L,3);
    lua_pushliteral(L,"");
    lua_call(L,2,1);
  }
  if (!(lua_toboolean(L,-1))) {
    lua_pop(L,1);
    lua_pushliteral(L,"air");
    const int lc55 = lua_equal(L,4,-1);
    lua_pop(L,1);
    lua_pushboolean(L,lc55);
    lua_pushboolean(L,!(lua_toboolean(L,-1)));
    lua_remove(L,-2);
    if (lua_toboolean(L,-1)) {
      lua_pop(L,1);
      lua_pushliteral(L,"fire:basic_flame");
      const int lc56 = lua_equal(L,4,-1);
      lua_pop(L,1);
      lua_pushboolean(L,lc56);
      lua_pushboolean(L,!(lua_toboolean(L,-1)));
      lua_remove(L,-2);
    }
  }
  const int lc57 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc57) {
    
    /* self.object:remove() */
    lua_pushliteral(L,"object");
    lua_gettable(L,1);
    lua_pushliteral(L,"remove");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_call(L,1,0);
    assert(lua_gettop(L) == 4);
  }
  lua_settop(L,lc53);
  assert(lua_gettop(L) == 4);
  
  /* if math.random(1,2)==2 then */
  enum { lc58 = 4 };
  lua_getfield(L,LUA_ENVIRONINDEX,"math");
  lua_pushliteral(L,"random");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,1);
  lua_pushnumber(L,2);
  lua_call(L,2,1);
  lua_pushnumber(L,2);
  const int lc59 = lua_equal(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc59);
  const int lc60 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc60) {
    
    /* minetest.env:set_node(pos, {name="fire:basic_flame"}) */
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"env");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushliteral(L,"set_node");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_pushvalue(L,3);
    lua_createtable(L,0,1);
    lua_pushliteral(L,"name");
    lua_pushliteral(L,"fire:basic_flame");
    lua_rawset(L,-3);
    lua_call(L,3,0);
    assert(lua_gettop(L) == 4);
  }
  lua_settop(L,lc58);
  assert(lua_gettop(L) == 4);
  
  /* if math.random(1,6)==1 then */
  enum { lc61 = 4 };
  lua_getfield(L,LUA_ENVIRONINDEX,"math");
  lua_pushliteral(L,"random");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,1);
  lua_pushnumber(L,6);
  lua_call(L,2,1);
  lua_pushnumber(L,1);
  const int lc62 = lua_equal(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc62);
  const int lc63 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc63) {
    
    /* dx = math.random(-1,1) */
    lua_getfield(L,LUA_ENVIRONINDEX,"math");
    lua_pushliteral(L,"random");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,-1);
    lua_pushnumber(L,1);
    lua_call(L,2,1);
    lua_setfield(L,LUA_ENVIRONINDEX,"dx");
    assert(lua_gettop(L) == 4);
    
    /* dy = math.random(-1,1) */
    lua_getfield(L,LUA_ENVIRONINDEX,"math");
    lua_pushliteral(L,"random");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,-1);
    lua_pushnumber(L,1);
    lua_call(L,2,1);
    lua_setfield(L,LUA_ENVIRONINDEX,"dy");
    assert(lua_gettop(L) == 4);
    
    /* dz = math.random(-1,1) */
    lua_getfield(L,LUA_ENVIRONINDEX,"math");
    lua_pushliteral(L,"random");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,-1);
    lua_pushnumber(L,1);
    lua_call(L,2,1);
    lua_setfield(L,LUA_ENVIRONINDEX,"dz");
    assert(lua_gettop(L) == 4);
    
    /* local p = {x=pos.x+dx, y=pos.y+dy, z=pos.z+dz} */
    lua_createtable(L,0,3);
    lua_pushliteral(L,"x");
    lua_pushliteral(L,"x");
    lua_gettable(L,3);
    lua_getfield(L,LUA_ENVIRONINDEX,"dx");
    lc_add(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"y");
    lua_pushliteral(L,"y");
    lua_gettable(L,3);
    lua_getfield(L,LUA_ENVIRONINDEX,"dy");
    lc_add(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"z");
    lua_pushliteral(L,"z");
    lua_gettable(L,3);
    lua_getfield(L,LUA_ENVIRONINDEX,"dz");
    lc_add(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    assert(lua_gettop(L) == 5);
    
    /* local n = minetest.env:get_node(p).name */
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"env");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushliteral(L,"get_node");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_pushvalue(L,5);
    lua_call(L,2,1);
    lua_pushliteral(L,"name");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    assert(lua_gettop(L) == 6);
    
    /* if n=="air" then */
    enum { lc64 = 6 };
    lua_pushliteral(L,"air");
    const int lc65 = lua_equal(L,6,-1);
    lua_pop(L,1);
    lua_pushboolean(L,lc65);
    const int lc66 = lua_toboolean(L,-1);
    lua_pop(L,1);
    if (lc66) {
      
      /* minetest.env:set_node(p, {name="fire:basic_flame"}) */
      lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
      lua_pushliteral(L,"env");
      lua_gettable(L,-2);
      lua_remove(L,-2);
      lua_pushliteral(L,"set_node");
      lua_gettable(L,-2);
      lua_insert(L,-2);
      lua_pushvalue(L,5);
      lua_createtable(L,0,1);
      lua_pushliteral(L,"name");
      lua_pushliteral(L,"fire:basic_flame");
      lua_rawset(L,-3);
      lua_call(L,3,0);
      assert(lua_gettop(L) == 6);
    }
    lua_settop(L,lc64);
    assert(lua_gettop(L) == 6);
  }
  lua_settop(L,lc61);
  assert(lua_gettop(L) == 4);
  return 0;
}


/* function(self, player) */
static int lcf68 (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* local p = player:getpos() */
  lua_pushvalue(L,2);
  lua_pushliteral(L,"getpos");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 3);
  
  /* nssm:gas_explosion(p) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"gas_explosion");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,3);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* function(self, pos, node) */
static int lcf69 (lua_State * L) {
  enum { lc_nformalargs = 3 };
  lua_settop(L,3);
  
  /* nssm:gas_explosion(pos) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"gas_explosion");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,2);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 3);
  return 0;
}


/* name: nssm:gas_explosion
 * function(pos) */
static int lcf1_nssm_gas_explosion (lua_State * L) {
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* if minetest.is_protected(pos, "") then */
  enum { lc70 = 2 };
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"is_protected");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushvalue(L,2);
  lua_pushliteral(L,"");
  lua_call(L,2,1);
  const int lc71 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc71) {
    
    /* return */
    return 0;
    assert(lua_gettop(L) == 2);
  }
  lua_settop(L,lc70);
  assert(lua_gettop(L) == 2);
  
  /* for dx=-2,2 do */
  lua_pushnumber(L,-2);
  lua_pushnumber(L,2);
  if (!((lua_isnumber(L,-2) && lua_isnumber(L,-1)))) {
    luaL_error(L,"'for' limit must be a number");
  }
  double lc72_var = lua_tonumber(L,-2);
  const double lc73_limit = lua_tonumber(L,-1);
  const double lc74_step = 1;
  lua_pop(L,2);
  enum { lc75 = 2 };
  while ((((lc74_step > 0) && (lc72_var <= lc73_limit)) || ((lc74_step <= 0) && (lc72_var >= lc73_limit)))) {
    
    /* internal: local dx at index 3 */
    lua_pushnumber(L,lc72_var);
    
    /* for dy=-1,4 do */
    lua_pushnumber(L,-1);
    lua_pushnumber(L,4);
    if (!((lua_isnumber(L,-2) && lua_isnumber(L,-1)))) {
      luaL_error(L,"'for' limit must be a number");
    }
    double lc76_var = lua_tonumber(L,-2);
    const double lc77_limit = lua_tonumber(L,-1);
    const double lc78_step = 1;
    lua_pop(L,2);
    enum { lc79 = 3 };
    while ((((lc78_step > 0) && (lc76_var <= lc77_limit)) || ((lc78_step <= 0) && (lc76_var >= lc77_limit)))) {
      
      /* internal: local dy at index 4 */
      lua_pushnumber(L,lc76_var);
      
      /* for dz=-2,2 do */
      lua_pushnumber(L,-2);
      lua_pushnumber(L,2);
      if (!((lua_isnumber(L,-2) && lua_isnumber(L,-1)))) {
        luaL_error(L,"'for' limit must be a number");
      }
      double lc80_var = lua_tonumber(L,-2);
      const double lc81_limit = lua_tonumber(L,-1);
      const double lc82_step = 1;
      lua_pop(L,2);
      enum { lc83 = 4 };
      while ((((lc82_step > 0) && (lc80_var <= lc81_limit)) || ((lc82_step <= 0) && (lc80_var >= lc81_limit)))) {
        
        /* internal: local dz at index 5 */
        lua_pushnumber(L,lc80_var);
        
        /* local p = {x=pos.x+dx, y=pos.y+dy, z=pos.z+dz} */
        lua_createtable(L,0,3);
        lua_pushliteral(L,"x");
        lua_pushliteral(L,"x");
        lua_gettable(L,2);
        lc_add(L,-1,3);
        lua_remove(L,-2);
        lua_rawset(L,-3);
        lua_pushliteral(L,"y");
        lua_pushliteral(L,"y");
        lua_gettable(L,2);
        lc_add(L,-1,4);
        lua_remove(L,-2);
        lua_rawset(L,-3);
        lua_pushliteral(L,"z");
        lua_pushliteral(L,"z");
        lua_gettable(L,2);
        lc_add(L,-1,5);
        lua_remove(L,-2);
        lua_rawset(L,-3);
        assert(lua_gettop(L) == 6);
        
        /* if minetest.is_protected(p, "") then */
        enum { lc84 = 6 };
        lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
        lua_pushliteral(L,"is_protected");
        lua_gettable(L,-2);
        lua_remove(L,-2);
        lua_pushvalue(L,6);
        lua_pushliteral(L,"");
        lua_call(L,2,1);
        const int lc85 = lua_toboolean(L,-1);
        lua_pop(L,1);
        if (lc85) {
          
          /* return */
          return 0;
          assert(lua_gettop(L) == 6);
        }
        lua_settop(L,lc84);
        assert(lua_gettop(L) == 6);
        
        /* local n = minetest.env:get_node(p).name */
        lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
        lua_pushliteral(L,"env");
        lua_gettable(L,-2);
        lua_remove(L,-2);
        lua_pushliteral(L,"get_node");
        lua_gettable(L,-2);
        lua_insert(L,-2);
        lua_pushvalue(L,6);
        lua_call(L,2,1);
        lua_pushliteral(L,"name");
        lua_gettable(L,-2);
        lua_remove(L,-2);
        assert(lua_gettop(L) == 7);
        
        /* if n== "air" then */
        enum { lc86 = 7 };
        lua_pushliteral(L,"air");
        const int lc87 = lua_equal(L,7,-1);
        lua_pop(L,1);
        lua_pushboolean(L,lc87);
        const int lc88 = lua_toboolean(L,-1);
        lua_pop(L,1);
        if (lc88) {
          
          /* minetest.set_node(p, {name="nssm:venomous_gas"}) */
          lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
          lua_pushliteral(L,"set_node");
          lua_gettable(L,-2);
          lua_remove(L,-2);
          lua_pushvalue(L,6);
          lua_createtable(L,0,1);
          lua_pushliteral(L,"name");
          lua_pushliteral(L,"nssm:venomous_gas");
          lua_rawset(L,-3);
          lua_call(L,2,0);
          assert(lua_gettop(L) == 7);
        }
        lua_settop(L,lc86);
        assert(lua_gettop(L) == 7);
        
        /* internal: stack cleanup on scope exit */
        lua_pop(L,3);
        lc80_var += lc82_step;
      }
      lua_settop(L,lc83);
      assert(lua_gettop(L) == 4);
      
      /* internal: stack cleanup on scope exit */
      lua_pop(L,1);
      lc76_var += lc78_step;
    }
    lua_settop(L,lc79);
    assert(lua_gettop(L) == 3);
    
    /* internal: stack cleanup on scope exit */
    lua_pop(L,1);
    lc72_var += lc74_step;
  }
  lua_settop(L,lc75);
  assert(lua_gettop(L) == 2);
  return 0;
}


/* warning: assumes indices in range LUA_REGISTRYINDEX < x < 0 are relative. */
static int lc_le(lua_State * L, int idxa, int idxb) {
  if (lua_type(L,idxa) == LUA_TNUMBER && lua_type(L,idxb) == LUA_TNUMBER) {
    return lua_tonumber(L,idxa) <= lua_tonumber(L,idxb);
  }
  else if (lua_type(L,idxa) == LUA_TSTRING && lua_type(L,idxb) == LUA_TSTRING) {
    /* result similar to lvm.c l_strcmp */
    return lua_lessthan(L,idxa,idxb) || lua_rawequal(L,idxa,idxb);
  }
  else if (luaL_getmetafield(L,idxa,"__le")||luaL_getmetafield(L,idxb,"__le")) {
    lua_pushvalue(L,idxa < 0 && idxa > LUA_REGISTRYINDEX ? idxa-1 : idxa);
    lua_pushvalue(L,idxb < 0 && idxb > LUA_REGISTRYINDEX ? idxb-2 : idxb);
    lua_call(L,2,1);
    const int result = lua_toboolean(L,-1);
    lua_pop(L,1);
    return result;
  }
  else if (luaL_getmetafield(L,idxa,"__lt")||luaL_getmetafield(L,idxb,"__lt")) {
    lua_pushvalue(L,idxb < 0 && idxb > LUA_REGISTRYINDEX ? idxb-1 : idxb);
    lua_pushvalue(L,idxa < 0 && idxa > LUA_REGISTRYINDEX ? idxa-2 : idxa);
    lua_call(L,2,1);
    const int result = ! lua_toboolean(L,-1);
    lua_pop(L,1);
    return result;
  }
  else {
    return luaL_error(L, "attempt to compare");
  }
}


/* function(self, dtime) */
static int lcf109 (lua_State * L) {
  lua_checkstack(L,21);
  enum { lc_nformalargs = 2 };
  lua_settop(L,2);
  
  /* local pos = self.object:getpos() */
  lua_pushliteral(L,"object");
  lua_gettable(L,1);
  lua_pushliteral(L,"getpos");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 3);
  
  /* local n = minetest.env:get_node(pos).name */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"env");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"get_node");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,3);
  lua_call(L,2,1);
  lua_pushliteral(L,"name");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  assert(lua_gettop(L) == 4);
  
  /* if self.timer == 0 then */
  enum { lc89 = 4 };
  lua_pushliteral(L,"timer");
  lua_gettable(L,1);
  lua_pushnumber(L,0);
  const int lc90 = lua_equal(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc90);
  const int lc91 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc91) {
    
    /* self.timer = os.time() */
    lua_getfield(L,LUA_ENVIRONINDEX,"os");
    lua_pushliteral(L,"time");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_call(L,0,1);
    lua_pushliteral(L,"timer");
    lua_insert(L,-2);
    lua_settable(L,1);
    assert(lua_gettop(L) == 4);
  }
  lua_settop(L,lc89);
  assert(lua_gettop(L) == 4);
  
  /* if os.time() - self.timer > 8 or minetest.is_protected(pos, "") then */
  enum { lc92 = 4 };
  lua_pushnumber(L,8);
  lua_getfield(L,LUA_ENVIRONINDEX,"os");
  lua_pushliteral(L,"time");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_call(L,0,1);
  lua_pushliteral(L,"timer");
  lua_gettable(L,1);
  lc_sub(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  const int lc93 = lua_lessthan(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc93);
  if (!(lua_toboolean(L,-1))) {
    lua_pop(L,1);
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"is_protected");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushvalue(L,3);
    lua_pushliteral(L,"");
    lua_call(L,2,1);
  }
  const int lc94 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc94) {
    
    /* self.object:remove() */
    lua_pushliteral(L,"object");
    lua_gettable(L,1);
    lua_pushliteral(L,"remove");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_call(L,1,0);
    assert(lua_gettop(L) == 4);
  }
  lua_settop(L,lc92);
  assert(lua_gettop(L) == 4);
  
  /* local objects = minetest.env:get_objects_inside_radius(pos, 1) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"env");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"get_objects_inside_radius");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,3);
  lua_pushnumber(L,1);
  lua_call(L,3,1);
  assert(lua_gettop(L) == 5);
  
  /* for _,obj in ipairs(objects) do
   * internal: local f, s, var = explist */
  enum { lc95 = 5 };
  lua_getfield(L,LUA_ENVIRONINDEX,"ipairs");
  lua_pushvalue(L,5);
  lua_call(L,1,3);
  while (1) {
    
    /* internal: local var_1, ..., var_n = f(s, var)
     *           if var_1 == nil then break end
     *           var = var_1 */
    lua_pushvalue(L,-3);
    lua_pushvalue(L,-3);
    lua_pushvalue(L,-3);
    lua_call(L,2,2);
    if (lua_isnil(L,-2)) {
      break;
    }
    lua_pushvalue(L,-2);
    lua_replace(L,-4);
    
    /* internal: local _ with idx 9
     * internal: local obj with idx 10 */
    
    
    /* local name = obj:get_entity_name() */
    lua_pushvalue(L,10);
    lua_pushliteral(L,"get_entity_name");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_call(L,1,1);
    assert(lua_gettop(L) == 11);
    
    /* if name~="nssm:roar_of_the_dragon" and name ~= "nssm:mese_dragon" then */
    enum { lc96 = 11 };
    lua_pushliteral(L,"nssm:roar_of_the_dragon");
    const int lc97 = lua_equal(L,11,-1);
    lua_pop(L,1);
    lua_pushboolean(L,lc97);
    lua_pushboolean(L,!(lua_toboolean(L,-1)));
    lua_remove(L,-2);
    if (lua_toboolean(L,-1)) {
      lua_pop(L,1);
      lua_pushliteral(L,"nssm:mese_dragon");
      const int lc98 = lua_equal(L,11,-1);
      lua_pop(L,1);
      lua_pushboolean(L,lc98);
      lua_pushboolean(L,!(lua_toboolean(L,-1)));
      lua_remove(L,-2);
    }
    const int lc99 = lua_toboolean(L,-1);
    lua_pop(L,1);
    if (lc99) {
      
      /* obj:set_hp(obj:get_hp()-0.05) */
      lua_pushvalue(L,10);
      lua_pushliteral(L,"set_hp");
      lua_gettable(L,-2);
      lua_insert(L,-2);
      lua_pushvalue(L,10);
      lua_pushliteral(L,"get_hp");
      lua_gettable(L,-2);
      lua_insert(L,-2);
      lua_call(L,1,1);
      lua_pushnumber(L,0.05);
      lc_sub(L,-2,-1);
      lua_remove(L,-2);
      lua_remove(L,-2);
      lua_call(L,2,0);
      assert(lua_gettop(L) == 11);
      
      /* if (obj:get_hp() <= 0) then */
      enum { lc100 = 11 };
      lua_pushvalue(L,10);
      lua_pushliteral(L,"get_hp");
      lua_gettable(L,-2);
      lua_insert(L,-2);
      lua_call(L,1,1);
      lua_pushnumber(L,0);
      const int lc101 = lc_le(L,-2,-1);
      lua_pop(L,2);
      lua_pushboolean(L,lc101);
      const int lc102 = lua_toboolean(L,-1);
      lua_pop(L,1);
      if (lc102) {
        
        /* if (not obj:is_player()) and name ~= self.object:get_luaentity().name then */
        enum { lc103 = 11 };
        lua_pushvalue(L,10);
        lua_pushliteral(L,"is_player");
        lua_gettable(L,-2);
        lua_insert(L,-2);
        lua_call(L,1,1);
        lua_pushboolean(L,!(lua_toboolean(L,-1)));
        lua_remove(L,-2);
        if (lua_toboolean(L,-1)) {
          lua_pop(L,1);
          lua_pushliteral(L,"object");
          lua_gettable(L,1);
          lua_pushliteral(L,"get_luaentity");
          lua_gettable(L,-2);
          lua_insert(L,-2);
          lua_call(L,1,1);
          lua_pushliteral(L,"name");
          lua_gettable(L,-2);
          lua_remove(L,-2);
          const int lc104 = lua_equal(L,11,-1);
          lua_pop(L,1);
          lua_pushboolean(L,lc104);
          lua_pushboolean(L,!(lua_toboolean(L,-1)));
          lua_remove(L,-2);
        }
        const int lc105 = lua_toboolean(L,-1);
        lua_pop(L,1);
        if (lc105) {
          
          /* obj:remove() */
          lua_pushvalue(L,10);
          lua_pushliteral(L,"remove");
          lua_gettable(L,-2);
          lua_insert(L,-2);
          lua_call(L,1,0);
          assert(lua_gettop(L) == 11);
        }
        lua_settop(L,lc103);
        assert(lua_gettop(L) == 11);
      }
      lua_settop(L,lc100);
      assert(lua_gettop(L) == 11);
    }
    lua_settop(L,lc96);
    assert(lua_gettop(L) == 11);
    
    /* internal: stack cleanup on scope exit */
    lua_pop(L,3);
  }
  lua_settop(L,lc95);
  assert(lua_gettop(L) == 5);
  
  /* minetest.env:set_node(pos, {name="air"}) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"env");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"set_node");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,3);
  lua_createtable(L,0,1);
  lua_pushliteral(L,"name");
  lua_pushliteral(L,"air");
  lua_rawset(L,-3);
  lua_call(L,3,0);
  assert(lua_gettop(L) == 5);
  
  /* if math.random(1,2)==1 then */
  enum { lc106 = 5 };
  lua_getfield(L,LUA_ENVIRONINDEX,"math");
  lua_pushliteral(L,"random");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushnumber(L,1);
  lua_pushnumber(L,2);
  lua_call(L,2,1);
  lua_pushnumber(L,1);
  const int lc107 = lua_equal(L,-2,-1);
  lua_pop(L,2);
  lua_pushboolean(L,lc107);
  const int lc108 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc108) {
    
    /* dx = math.random(-1,1) */
    lua_getfield(L,LUA_ENVIRONINDEX,"math");
    lua_pushliteral(L,"random");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,-1);
    lua_pushnumber(L,1);
    lua_call(L,2,1);
    lua_setfield(L,LUA_ENVIRONINDEX,"dx");
    assert(lua_gettop(L) == 5);
    
    /* dy = math.random(-1,1) */
    lua_getfield(L,LUA_ENVIRONINDEX,"math");
    lua_pushliteral(L,"random");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,-1);
    lua_pushnumber(L,1);
    lua_call(L,2,1);
    lua_setfield(L,LUA_ENVIRONINDEX,"dy");
    assert(lua_gettop(L) == 5);
    
    /* dz = math.random(-1,1) */
    lua_getfield(L,LUA_ENVIRONINDEX,"math");
    lua_pushliteral(L,"random");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushnumber(L,-1);
    lua_pushnumber(L,1);
    lua_call(L,2,1);
    lua_setfield(L,LUA_ENVIRONINDEX,"dz");
    assert(lua_gettop(L) == 5);
    
    /* local p = {x=pos.x+dx, y=pos.y+dy, z=pos.z+dz} */
    lua_createtable(L,0,3);
    lua_pushliteral(L,"x");
    lua_pushliteral(L,"x");
    lua_gettable(L,3);
    lua_getfield(L,LUA_ENVIRONINDEX,"dx");
    lc_add(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"y");
    lua_pushliteral(L,"y");
    lua_gettable(L,3);
    lua_getfield(L,LUA_ENVIRONINDEX,"dy");
    lc_add(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    lua_pushliteral(L,"z");
    lua_pushliteral(L,"z");
    lua_gettable(L,3);
    lua_getfield(L,LUA_ENVIRONINDEX,"dz");
    lc_add(L,-2,-1);
    lua_remove(L,-2);
    lua_remove(L,-2);
    lua_rawset(L,-3);
    assert(lua_gettop(L) == 6);
    
    /* minetest.env:set_node(p, {name="air"}) */
    lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
    lua_pushliteral(L,"env");
    lua_gettable(L,-2);
    lua_remove(L,-2);
    lua_pushliteral(L,"set_node");
    lua_gettable(L,-2);
    lua_insert(L,-2);
    lua_pushvalue(L,6);
    lua_createtable(L,0,1);
    lua_pushliteral(L,"name");
    lua_pushliteral(L,"air");
    lua_rawset(L,-3);
    lua_call(L,3,0);
    assert(lua_gettop(L) == 6);
  }
  lua_settop(L,lc106);
  assert(lua_gettop(L) == 5);
  return 0;
}


/* name: (main)
 * function(...) */
static int lcf_main (lua_State * L) {
  enum { lc_nformalargs = 0 };
  #ifndef NDEBUG
  const int lc_nactualargs = lua_gettop(L);
  #endif
  #ifndef NDEBUG
  const int lc_nextra = (lc_nactualargs - lc_nformalargs);
  #endif
  
  /* -- arrow (duck_arrow)
   * nssm:register_arrow("nssm:duck_father", {
   * 	visual = "sprite",
   * 	visual_size = {x = 1, y = 1},
   * 	textures = {"duck_egg.png"},
   * 	velocity = 8,
   * 	-- direct hit
   * 	hit_player = function(self, player)
   * 		local pos = self.object:getpos()
   * 		nssm:duck_explosion(pos)
   * 	end,
   * 
   * 	hit_mob = function(self, player)
   * 		local pos = self.object:getpos()
   * 		nssm:duck_explosion(pos)
   * 	end,
   * 
   * 	hit_node = function(self, pos, node)
   * 		nssm:duck_explosion(pos)
   * 	end,
   * 
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"register_arrow");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushliteral(L,"nssm:duck_father");
  lua_createtable(L,0,7);
  lua_pushliteral(L,"visual");
  lua_pushliteral(L,"sprite");
  lua_rawset(L,-3);
  lua_pushliteral(L,"visual_size");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"x");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"textures");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"duck_egg.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"velocity");
  lua_pushnumber(L,8);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_player");
  lua_pushcfunction(L,lcf1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_mob");
  lua_pushcfunction(L,lcf2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_node");
  lua_pushcfunction(L,lcf3);
  lua_rawset(L,-3);
  lua_call(L,3,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* function nssm:duck_explosion(pos)
   * 	pos.y = pos.y+1;
   * 	minetest.add_particlespawner({
   * 		amount = 10,
   * 		time = 0.2,
   * 		minpos = {x=pos.x-1, y=pos.y-1, z=pos.z-1},
   * 		maxpos = {x=pos.x+1, y=pos.y+4, z=pos.z+1},
   * 		minvel = {x=0, y=0, z=0},
   * 		maxvel = {x=1, y=1, z=1},
   * 		minacc = {x=-0.5,y=5,z=-0.5},
   * 		maxacc = {x=0.5,y=5,z=0.5},
   * 		minexptime = 1,
   * 		maxexptime = 3,
   * 		minsize = 4,
   * 		maxsize = 6,
   * 		collisiondetection = false,
   * 		vertical = false,
   * 		texture = "duck_egg_fragments.png",
   * 	})
   * 	core.after(0.4, function()
   * 		for dx = -2,2 do
   * 			pos = {x = pos.x+dx, y=pos.y; z=pos.z+dx}
   * 			minetest.add_particlespawner({
   * 				amount = 100,
   * 				time = 0.2,
   * 				minpos = {x=pos.x-1, y=pos.y-1, z=pos.z-1},
   * 				maxpos = {x=pos.x+1, y=pos.y+4, z=pos.z+1},
   * 				minvel = {x=0, y=0, z=0},
   * 				maxvel = {x=1, y=5, z=1},
   * 				minacc = {x=-0.5,y=5,z=-0.5},
   * 				maxacc = {x=0.5,y=5,z=0.5},
   * 				minexptime = 1,
   * 				maxexptime = 3,
   * 				minsize = 2,
   * 				maxsize = 4,
   * 				collisiondetection = false,
   * 				vertical = false,
   * 				texture = "tnt_smoke.png",
   * 			})
   * 			minetest.add_entity(pos, "nssm:duck")
   * 		end
   * 	end)
   * end */
  lua_pushcfunction(L,lcf1_nssm_duck_explosion);
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_insert(L,-2);
  lua_pushliteral(L,"duck_explosion");
  lua_insert(L,-2);
  lua_settable(L,-3);
  lua_pop(L,1);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* -- snow_arrow
   * nssm:register_arrow("nssm:snow_arrow", {
   * 	visual = "sprite",
   * 	visual_size = {x = 1, y = 1},
   * 	textures = {"transparent.png"},
   * 	velocity =20,
   * 	-- direct hit
   * 	hit_player = function(self, player)
   * 		local pos = self.object:getpos()
   * 		nssm:ice_explosion(pos)
   * 	end,
   * 
   * 	hit_mob = function(self, player)
   * 		local pos = self.object:getpos()
   * 		nssm:ice_explosion(pos)
   * 	end,
   * 	hit_node = function(self, pos, node)
   * 		nssm:ice_explosion(pos)
   * 	end,
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"register_arrow");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushliteral(L,"nssm:snow_arrow");
  lua_createtable(L,0,7);
  lua_pushliteral(L,"visual");
  lua_pushliteral(L,"sprite");
  lua_rawset(L,-3);
  lua_pushliteral(L,"visual_size");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"x");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"textures");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"transparent.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"velocity");
  lua_pushnumber(L,20);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_player");
  lua_pushcfunction(L,lcf10);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_mob");
  lua_pushcfunction(L,lcf11);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_node");
  lua_pushcfunction(L,lcf12);
  lua_rawset(L,-3);
  lua_call(L,3,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* function nssm:ice_explosion(pos)
   * 	for i=pos.x-math.random(0, 1), pos.x+math.random(0, 1), 1 do
   * 		for j=pos.y-1, pos.y+4, 1 do
   * 			for k=pos.z-math.random(0, 1), pos.z+math.random(0, 1), 1 do
   * 				minetest.set_node({x=i, y=j, z=k}, {name="default:ice"})
   * 			end
   * 		end
   * 	end
   * end */
  lua_pushcfunction(L,lcf1_nssm_ice_explosion);
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_insert(L,-2);
  lua_pushliteral(L,"ice_explosion");
  lua_insert(L,-2);
  lua_settable(L,-3);
  lua_pop(L,1);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* -- arrow manticore
   * nssm:register_arrow("nssm:spine", {
   * 	visual = "sprite",
   * 	visual_size = {x = 1, y = 1},
   * 	textures = {"manticore_spine_flying.png"},
   * 	velocity = 10,
   * 	-- direct hit
   * 	hit_player = function(self, player)
   * 		player:punch(self.object, 1.0, {
   * 			full_punch_interval = 1.0,
   * 			damage_groups = {fleshy = 2},
   * 		}, nil)
   * 	end,
   * 
   * 	hit_mob = function(self, player)
   * 		player:punch(self.object, 1.0, {
   * 			full_punch_interval = 1.0,
   * 			damage_groups = {fleshy = 2},
   * 		}, nil)
   * 	end,
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"register_arrow");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushliteral(L,"nssm:spine");
  lua_createtable(L,0,6);
  lua_pushliteral(L,"visual");
  lua_pushliteral(L,"sprite");
  lua_rawset(L,-3);
  lua_pushliteral(L,"visual_size");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"x");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"textures");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"manticore_spine_flying.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"velocity");
  lua_pushnumber(L,10);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_player");
  lua_pushcfunction(L,lcf25);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_mob");
  lua_pushcfunction(L,lcf26);
  lua_rawset(L,-3);
  lua_call(L,3,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* -- web arrow
   * nssm:register_arrow("nssm:webball", {
   * 	visual = "sprite",
   * 	visual_size = {x = 1, y = 1},
   * 	textures = {"web_ball.png"},
   * 	velocity = 8,
   * 	-- direct hit
   * 	hit_player = function(self, player)
   * 		local p = player:getpos()
   * 		nssm:explosion_web(p)
   * 	end,
   * 
   * 	hit_mob = function(self, player)
   * 		player:punch(self.object, 1.0, {
   * 			full_punch_interval = 1.0,
   * 			damage_groups = {fleshy = 1},
   * 		}, nil)
   * 	end,
   * 
   * 	hit_node = function(self, pos, node)
   * 		nssm:explosion_web(pos)
   * 	end
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"register_arrow");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushliteral(L,"nssm:webball");
  lua_createtable(L,0,7);
  lua_pushliteral(L,"visual");
  lua_pushliteral(L,"sprite");
  lua_rawset(L,-3);
  lua_pushliteral(L,"visual_size");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"x");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"textures");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"web_ball.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"velocity");
  lua_pushnumber(L,8);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_player");
  lua_pushcfunction(L,lcf27);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_mob");
  lua_pushcfunction(L,lcf28);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_node");
  lua_pushcfunction(L,lcf29);
  lua_rawset(L,-3);
  lua_call(L,3,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* function nssm:explosion_web(pos)
   * 	if minetest.is_protected(pos, "") then
   * 		return
   * 	end
   * 	pos.y = nssm:round(pos.y)
   *     for i=pos.x-1, pos.x+1, 1 do
   * 		for j=pos.y-3, pos.y, 1 do
   * 			for k=pos.z-1, pos.z+1, 1 do
   * 				local p = {x=i,y=j,z=k}
   * 				local k = {x=i,y=j+1,z=k}
   * 				local current = minetest.env:get_node(p).name
   * 				local ontop  = minetest.env:get_node(k).name
   * 				if 	(current ~= "air") and
   * 					(current ~= "nssm:web") and
   * 					(ontop == "air") and not
   * 					minetest.is_protected(p,"") and not
   * 					minetest.is_protected(k,"") then
   * 						minetest.set_node(k, {name="nssm:web"})
   * 				end
   * 			end
   * 		end
   * 	end
   * end */
  lua_pushcfunction(L,lcf1_nssm_explosion_web);
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_insert(L,-2);
  lua_pushliteral(L,"explosion_web");
  lua_insert(L,-2);
  lua_settable(L,-3);
  lua_pop(L,1);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* -- arrow=>phoenix arrow
   * nssm:register_arrow("nssm:phoenix_arrow", {
   * 	visual = "sprite",
   * 	visual_size = {x = 1, y = 1},
   * 	textures = {"transparent.png"},
   * 	velocity = 8,
   * 	-- direct hit
   * 	hit_player = function(self, player)
   * 	end,
   * 
   * 	on_step = function(self, dtime)
   * 
   * 		local pos = self.object:getpos()
   * 
   * 		local n = minetest.env:get_node(pos).name
   * 
   * 		if self.timer == 0 then
   * 			self.timer = os.time()
   * 		end
   * 
   * 		if os.time() - self.timer > 5 or minetest.is_protected(pos, "") or ((n~="air") and (n~="fire:basic_flame")) then
   * 			self.object:remove()
   * 		end
   * 
   * 		if math.random(1,2)==2 then
   * 			minetest.env:set_node(pos, {name="fire:basic_flame"})
   * 		end
   * 
   * 		if math.random(1,6)==1 then
   * 			dx = math.random(-1,1)
   * 			dy = math.random(-1,1)
   * 			dz = math.random(-1,1)
   * 			local p = {x=pos.x+dx, y=pos.y+dy, z=pos.z+dz}
   * 			local n = minetest.env:get_node(p).name
   * 			if n=="air" then
   * 				minetest.env:set_node(p, {name="fire:basic_flame"})
   * 			end
   * 		end
   * 
   * 	end,
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"register_arrow");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushliteral(L,"nssm:phoenix_arrow");
  lua_createtable(L,0,6);
  lua_pushliteral(L,"visual");
  lua_pushliteral(L,"sprite");
  lua_rawset(L,-3);
  lua_pushliteral(L,"visual_size");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"x");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"textures");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"transparent.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"velocity");
  lua_pushnumber(L,8);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_player");
  lua_pushcfunction(L,lcf49);
  lua_rawset(L,-3);
  lua_pushliteral(L,"on_step");
  lua_pushcfunction(L,lcf67);
  lua_rawset(L,-3);
  lua_call(L,3,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* nssm:register_arrow("nssm:super_gas", {
   * 	visual = "sprite",
   * 	visual_size = {x = 1, y = 1},
   * 	textures = {"transparent.png"},
   * 	velocity = 8,
   * 	-- direct hit
   * 	hit_player = function(self, player)
   * 		local p = player:getpos()
   * 		nssm:gas_explosion(p)
   * 	end,
   * 
   * 	hit_node = function(self, pos, node)
   * 		nssm:gas_explosion(pos)
   * 	end
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"register_arrow");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushliteral(L,"nssm:super_gas");
  lua_createtable(L,0,6);
  lua_pushliteral(L,"visual");
  lua_pushliteral(L,"sprite");
  lua_rawset(L,-3);
  lua_pushliteral(L,"visual_size");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"x");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"textures");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"transparent.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"velocity");
  lua_pushnumber(L,8);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_player");
  lua_pushcfunction(L,lcf68);
  lua_rawset(L,-3);
  lua_pushliteral(L,"hit_node");
  lua_pushcfunction(L,lcf69);
  lua_rawset(L,-3);
  lua_call(L,3,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* function nssm:gas_explosion(pos)
   * 	if minetest.is_protected(pos, "") then
   * 		return
   * 	end
   * 	for dx=-2,2 do
   * 		for dy=-1,4 do
   * 			for dz=-2,2 do
   * 				local p = {x=pos.x+dx, y=pos.y+dy, z=pos.z+dz}
   * 				if minetest.is_protected(p, "") then
   * 					return
   * 				end
   * 				local n = minetest.env:get_node(p).name
   * 				if n== "air" then
   * 					minetest.set_node(p, {name="nssm:venomous_gas"})
   * 				end
   * 			end
   * 		end
   * 	end
   * end */
  lua_pushcfunction(L,lcf1_nssm_gas_explosion);
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_insert(L,-2);
  lua_pushliteral(L,"gas_explosion");
  lua_insert(L,-2);
  lua_settable(L,-3);
  lua_pop(L,1);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* --
   * nssm:register_arrow("nssm:roar_of_the_dragon", {
   * 	visual = "sprite",
   * 	visual_size = {x = 1, y = 1},
   * 	textures = {"transparent.png"},
   * 	velocity = 10,
   * 
   * 	on_step = function(self, dtime)
   * 
   * 		local pos = self.object:getpos()
   * 
   * 		local n = minetest.env:get_node(pos).name
   * 
   * 		if self.timer == 0 then
   * 			self.timer = os.time()
   * 		end
   * 
   * 		if os.time() - self.timer > 8 or minetest.is_protected(pos, "") then
   * 			self.object:remove()
   * 		end
   * 
   * 		local objects = minetest.env:get_objects_inside_radius(pos, 1)
   * 	    for _,obj in ipairs(objects) do
   * 			local name = obj:get_entity_name()
   * 			if name~="nssm:roar_of_the_dragon" and name ~= "nssm:mese_dragon" then
   * 		        obj:set_hp(obj:get_hp()-0.05)
   * 		        if (obj:get_hp() <= 0) then
   * 		            if (not obj:is_player()) and name ~= self.object:get_luaentity().name then
   * 		                obj:remove()
   * 		            end
   * 		        end
   * 			end
   * 	    end
   * 
   * 		minetest.env:set_node(pos, {name="air"})
   * 		if math.random(1,2)==1 then
   * 			dx = math.random(-1,1)
   * 			dy = math.random(-1,1)
   * 			dz = math.random(-1,1)
   * 			local p = {x=pos.x+dx, y=pos.y+dy, z=pos.z+dz}
   * 			minetest.env:set_node(p, {name="air"})
   * 		end
   * 	end
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"nssm");
  lua_pushliteral(L,"register_arrow");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushliteral(L,"nssm:roar_of_the_dragon");
  lua_createtable(L,0,5);
  lua_pushliteral(L,"visual");
  lua_pushliteral(L,"sprite");
  lua_rawset(L,-3);
  lua_pushliteral(L,"visual_size");
  lua_createtable(L,0,2);
  lua_pushliteral(L,"x");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_pushliteral(L,"textures");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"transparent.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"velocity");
  lua_pushnumber(L,10);
  lua_rawset(L,-3);
  lua_pushliteral(L,"on_step");
  lua_pushcfunction(L,lcf109);
  lua_rawset(L,-3);
  lua_call(L,3,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  return 0;
}


/* from lua.c */
static int traceback (lua_State *L) {
  if (!lua_isstring(L, 1))  /* 'message' not a string? */
    return 1;  /* keep it intact */
  lua_getfield(L, LUA_GLOBALSINDEX, "debug");
  if (!lua_istable(L, -1)) {
    lua_pop(L, 1);
    return 1;
  }
  lua_getfield(L, -1, "traceback");
  if (!lua_isfunction(L, -1)) {
    lua_pop(L, 2);
    return 1;
  }
  lua_pushvalue(L, 1);  /* pass error message */
  lua_pushinteger(L, 2);  /* skip this function and traceback */
  lua_call(L, 2, 1);  /* call debug.traceback */
  return 1;
}


static void lc_l_message (const char *pname, const char *msg) {
  if (pname) fprintf(stderr, "%s: ", pname);
  fprintf(stderr, "%s\n", msg);
  fflush(stderr);
}

static int lc_report (lua_State *L, int status) {
  if (status && !lua_isnil(L, -1)) {
    const char *msg = lua_tostring(L, -1);
    if (msg == NULL) msg = "(error object is not a string)";
    /*FIX-IMROVE:progname*/
    lc_l_message("lua", msg);
    lua_pop(L, 1);
  }
  return status;
}

static int lc_docall (lua_State *L, int narg, int clear) {
  int status;
  int base = lua_gettop(L) - narg;  /* function index */
  lua_pushcfunction(L, traceback);  /* push traceback function */
  lua_insert(L, base);  /* put it under chunk and args */
  /*FIX? signal(SIGINT, laction); */
  status = lua_pcall(L, narg, (clear ? 0 : LUA_MULTRET), base);
  /*FIX? signal(SIGINT, SIG_DFL); */
  lua_remove(L, base);  /* remove traceback function */
  /* force a complete garbage collection in case of errors */
  if (status != 0) lua_gc(L, LUA_GCCOLLECT, 0);
  return status;
}

static int lc_dofile (lua_State *L, const char *name) {
  int status = luaL_loadfile(L, name) || lc_docall(L, 0, 1);
  return lc_report(L, status);
}

static int lc_dostring (lua_State *L, const char *s, const char *name) {
  int status = luaL_loadbuffer(L, s, strlen(s), name) || lc_docall(L, 0, 1);
  return lc_report(L, status);
}

static int lc_handle_luainit (lua_State *L) {
  const char *init = getenv(LUA_INIT);
  if (init == NULL) return 0;  /* status OK */
  else if (init[0] == '@')
    return lc_dofile(L, init+1);
  else
    return lc_dostring(L, init, "=" LUA_INIT);
}


typedef struct {
  int c;
  const char ** v;
} lc_args_t;


/* create global arg table */
static void lc_createarg(lua_State * L, const lc_args_t * const args) {
  int i;
  lua_newtable(L);
  for (i=0; i < args->c; i++) {
    lua_pushstring(L, args->v[i]);
    lua_rawseti(L, -2, i);
  }
  lua_setglobal(L, "arg");
}


int lc_pmain_mod_nssm_darts(lua_State * L) {
  luaL_openlibs(L);

  lua_pushcfunction(L, traceback);

  const int status1 = lc_handle_luainit(L);
  if (status1 != 0) return 0;

  /* note: IMPROVE: closure not always needed here */
  lua_newtable(L); /* closure table */
  lua_pushcclosure(L, lcf_main, 1);

  int status2 = lua_pcall(L, 0, 0, -2);
  if (status2 != 0) {
    const char * msg = lua_tostring(L,-1);
    if (msg == NULL) msg = "(error object is not a string)";
    fputs(msg, stderr);
  }
  return 0;
}


