/* WARNING: This file was automatically generated by lua2c. */

#ifdef __cplusplus
extern "C" {
#endif
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#ifdef __cplusplus
}
#endif
#include <stdio.h>
#include <stdlib.h>


#include <string.h>


#include <assert.h>

/* function (self, pos, node, dtime) */
static int lcf7 (lua_State * L) {
  enum { lc_nformalargs = 4 };
  lua_settop(L,4);
  
  /* local pos = self.object:getpos() */
  lua_pushliteral(L,"object");
  lua_gettable(L,1);
  lua_pushliteral(L,"getpos");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 5);
  
  /* local n = minetest.env:get_node(pos).name */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"env");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"get_node");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,5);
  lua_call(L,2,1);
  lua_pushliteral(L,"name");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  assert(lua_gettop(L) == 6);
  
  /* if n ~= "default:nyancat_rainbow" then */
  enum { lc1 = 6 };
  lua_pushliteral(L,"default:nyancat_rainbow");
  const int lc2 = lua_equal(L,6,-1);
  lua_pop(L,1);
  lua_pushboolean(L,lc2);
  lua_pushboolean(L,!(lua_toboolean(L,-1)));
  lua_remove(L,-2);
  const int lc3 = lua_toboolean(L,-1);
  lua_pop(L,1);
  if (lc3) {
    
    /* if n=="air" then */
    enum { lc4 = 6 };
    lua_pushliteral(L,"air");
    const int lc5 = lua_equal(L,6,-1);
    lua_pop(L,1);
    lua_pushboolean(L,lc5);
    const int lc6 = lua_toboolean(L,-1);
    lua_pop(L,1);
    if (lc6) {
      
      /* minetest.env:set_node(pos, {name="default:nyancat_rainbow"}) */
      lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
      lua_pushliteral(L,"env");
      lua_gettable(L,-2);
      lua_remove(L,-2);
      lua_pushliteral(L,"set_node");
      lua_gettable(L,-2);
      lua_insert(L,-2);
      lua_pushvalue(L,5);
      lua_createtable(L,0,1);
      lua_pushliteral(L,"name");
      lua_pushliteral(L,"default:nyancat_rainbow");
      lua_rawset(L,-3);
      lua_call(L,3,0);
      assert(lua_gettop(L) == 6);
    }
    else {
      
      /* else
       * minetest.env:set_node(pos, {name="default:nyancat"}) */
      lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
      lua_pushliteral(L,"env");
      lua_gettable(L,-2);
      lua_remove(L,-2);
      lua_pushliteral(L,"set_node");
      lua_gettable(L,-2);
      lua_insert(L,-2);
      lua_pushvalue(L,5);
      lua_createtable(L,0,1);
      lua_pushliteral(L,"name");
      lua_pushliteral(L,"default:nyancat");
      lua_rawset(L,-3);
      lua_call(L,3,0);
      assert(lua_gettop(L) == 6);
      
      /* self.object:remove() */
      lua_pushliteral(L,"object");
      lua_gettable(L,1);
      lua_pushliteral(L,"remove");
      lua_gettable(L,-2);
      lua_insert(L,-2);
      lua_call(L,1,0);
      assert(lua_gettop(L) == 6);
    }
    lua_settop(L,lc4);
    assert(lua_gettop(L) == 6);
  }
  lua_settop(L,lc1);
  assert(lua_gettop(L) == 6);
  return 0;
}


/* __add metamethod handler.
 * warning: assumes indices in range LUA_REGISTRYINDEX < x < 0 are relative. */
static void lc_add(lua_State * L, int idxa, int idxb) {
  if (lua_isnumber(L,idxa) && lua_isnumber(L,idxb)) {
    lua_pushnumber(L,lua_tonumber(L,idxa) + lua_tonumber(L,idxb));
  }
  else {
    if (luaL_getmetafield(L,idxa,"__add")||luaL_getmetafield(L,idxb,"__add")) {
      lua_pushvalue(L,idxa < 0 && idxa > LUA_REGISTRYINDEX ? idxa-1 : idxa);
      lua_pushvalue(L,idxb < 0 && idxb > LUA_REGISTRYINDEX ? idxb-2 : idxb);
      lua_call(L,2,1);
    }
    else {
      luaL_error(L, "attempt to perform arithmetic");
    }
  }
}


/* __mul metamethod handler.
 * warning: assumes indices in range LUA_REGISTRYINDEX < x < 0 are relative. */
static void lc_mul(lua_State * L, int idxa, int idxb) {
  if (lua_isnumber(L,idxa) && lua_isnumber(L,idxb)) {
    lua_pushnumber(L,lua_tonumber(L,idxa) * lua_tonumber(L,idxb));
  }
  else {
    if (luaL_getmetafield(L,idxa,"__mul")||luaL_getmetafield(L,idxb,"__mul")) {
      lua_pushvalue(L,idxa < 0 && idxa > LUA_REGISTRYINDEX ? idxa-1 : idxa);
      lua_pushvalue(L,idxb < 0 && idxb > LUA_REGISTRYINDEX ? idxb-2 : idxb);
      lua_call(L,2,1);
    }
    else {
      luaL_error(L, "attempt to perform arithmetic");
    }
  }
}


/* function(itemstack, placer, pointed_thing) */
static int lcf8 (lua_State * L) {
  enum { lc_nformalargs = 3 };
  lua_settop(L,3);
  
  /* local dir = placer:get_look_dir() */
  lua_pushvalue(L,2);
  lua_pushliteral(L,"get_look_dir");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 4);
  
  /* local playerpos = placer:getpos() */
  lua_pushvalue(L,2);
  lua_pushliteral(L,"getpos");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_call(L,1,1);
  assert(lua_gettop(L) == 5);
  
  /* local obj = minetest.env:add_entity({x=playerpos.x+0+dir.x,y=playerpos.y+2+dir.y,z=playerpos.z+0+dir.z}, "nssm:rainbow") */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"env");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"add_entity");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_createtable(L,0,3);
  lua_pushliteral(L,"x");
  lua_pushliteral(L,"x");
  lua_gettable(L,5);
  lua_pushnumber(L,0);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"x");
  lua_gettable(L,4);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushliteral(L,"y");
  lua_gettable(L,5);
  lua_pushnumber(L,2);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"y");
  lua_gettable(L,4);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"z");
  lua_pushliteral(L,"z");
  lua_gettable(L,5);
  lua_pushnumber(L,0);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"z");
  lua_gettable(L,4);
  lc_add(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"nssm:rainbow");
  lua_call(L,3,1);
  assert(lua_gettop(L) == 6);
  
  /* local vec = {x=dir.x*6,y=dir.y*6,z=dir.z*6} */
  lua_createtable(L,0,3);
  lua_pushliteral(L,"x");
  lua_pushliteral(L,"x");
  lua_gettable(L,4);
  lua_pushnumber(L,6);
  lc_mul(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"y");
  lua_pushliteral(L,"y");
  lua_gettable(L,4);
  lua_pushnumber(L,6);
  lc_mul(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  lua_pushliteral(L,"z");
  lua_pushliteral(L,"z");
  lua_gettable(L,4);
  lua_pushnumber(L,6);
  lc_mul(L,-2,-1);
  lua_remove(L,-2);
  lua_remove(L,-2);
  lua_rawset(L,-3);
  assert(lua_gettop(L) == 7);
  
  /* obj:setvelocity(vec) */
  lua_pushvalue(L,6);
  lua_pushliteral(L,"setvelocity");
  lua_gettable(L,-2);
  lua_insert(L,-2);
  lua_pushvalue(L,7);
  lua_call(L,2,0);
  assert(lua_gettop(L) == 7);
  
  /* return itemstack */
  lua_pushvalue(L,1);
  return 1;
  assert(lua_gettop(L) == 7);
}


/* name: (main)
 * function(...) */
static int lcf_main (lua_State * L) {
  enum { lc_nformalargs = 0 };
  #ifndef NDEBUG
  const int lc_nactualargs = lua_gettop(L);
  #endif
  #ifndef NDEBUG
  const int lc_nextra = (lc_nactualargs - lc_nformalargs);
  #endif
  
  /* --rainbow!
   * minetest.register_entity("nssm:rainbow", {
   * 	textures = {"transparent.png"},
   * 	velocity = 10,
   * 	on_step = function (self, pos, node, dtime)
   * 				local pos = self.object:getpos()
   * 								local n = minetest.env:get_node(pos).name
   * 								if n ~= "default:nyancat_rainbow" then
   * 									if n=="air" then
   * 										minetest.env:set_node(pos, {name="default:nyancat_rainbow"})
   * 									else
   * 									minetest.env:set_node(pos, {name="default:nyancat"})
   * 									self.object:remove()
   * 								end
   * 								end
   * 				end
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_entity");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"nssm:rainbow");
  lua_createtable(L,0,3);
  lua_pushliteral(L,"textures");
  lua_createtable(L,1,0);
  lua_pushliteral(L,"transparent.png");
  lua_rawseti(L,-2,1);
  lua_rawset(L,-3);
  lua_pushliteral(L,"velocity");
  lua_pushnumber(L,10);
  lua_rawset(L,-3);
  lua_pushliteral(L,"on_step");
  lua_pushcfunction(L,lcf7);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* minetest.register_tool("nssm:rainbow_staff", {
   * 	description = "Rainbow Staff",
   * 	inventory_image = "rainbow_staff.png",
   * 	on_use = function(itemstack, placer, pointed_thing)
   * 			local dir = placer:get_look_dir();
   * 			local playerpos = placer:getpos();
   * 			local obj = minetest.env:add_entity({x=playerpos.x+0+dir.x,y=playerpos.y+2+dir.y,z=playerpos.z+0+dir.z}, "nssm:rainbow")
   * 			local vec = {x=dir.x*6,y=dir.y*6,z=dir.z*6}
   * 			obj:setvelocity(vec)
   * 		return itemstack
   * 	end,
   * 	groups = {not_in_creative_inventory=1,}
   * }) */
  lua_getfield(L,LUA_ENVIRONINDEX,"minetest");
  lua_pushliteral(L,"register_tool");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"nssm:rainbow_staff");
  lua_createtable(L,0,4);
  lua_pushliteral(L,"description");
  lua_pushliteral(L,"Rainbow Staff");
  lua_rawset(L,-3);
  lua_pushliteral(L,"inventory_image");
  lua_pushliteral(L,"rainbow_staff.png");
  lua_rawset(L,-3);
  lua_pushliteral(L,"on_use");
  lua_pushcfunction(L,lcf8);
  lua_rawset(L,-3);
  lua_pushliteral(L,"groups");
  lua_createtable(L,0,1);
  lua_pushliteral(L,"not_in_creative_inventory");
  lua_pushnumber(L,1);
  lua_rawset(L,-3);
  lua_rawset(L,-3);
  lua_call(L,2,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  return 0;
}


/* from lua.c */
static int traceback (lua_State *L) {
  if (!lua_isstring(L, 1))  /* 'message' not a string? */
    return 1;  /* keep it intact */
  lua_getfield(L, LUA_GLOBALSINDEX, "debug");
  if (!lua_istable(L, -1)) {
    lua_pop(L, 1);
    return 1;
  }
  lua_getfield(L, -1, "traceback");
  if (!lua_isfunction(L, -1)) {
    lua_pop(L, 2);
    return 1;
  }
  lua_pushvalue(L, 1);  /* pass error message */
  lua_pushinteger(L, 2);  /* skip this function and traceback */
  lua_call(L, 2, 1);  /* call debug.traceback */
  return 1;
}


static void lc_l_message (const char *pname, const char *msg) {
  if (pname) fprintf(stderr, "%s: ", pname);
  fprintf(stderr, "%s\n", msg);
  fflush(stderr);
}

static int lc_report (lua_State *L, int status) {
  if (status && !lua_isnil(L, -1)) {
    const char *msg = lua_tostring(L, -1);
    if (msg == NULL) msg = "(error object is not a string)";
    /*FIX-IMROVE:progname*/
    lc_l_message("lua", msg);
    lua_pop(L, 1);
  }
  return status;
}

static int lc_docall (lua_State *L, int narg, int clear) {
  int status;
  int base = lua_gettop(L) - narg;  /* function index */
  lua_pushcfunction(L, traceback);  /* push traceback function */
  lua_insert(L, base);  /* put it under chunk and args */
  /*FIX? signal(SIGINT, laction); */
  status = lua_pcall(L, narg, (clear ? 0 : LUA_MULTRET), base);
  /*FIX? signal(SIGINT, SIG_DFL); */
  lua_remove(L, base);  /* remove traceback function */
  /* force a complete garbage collection in case of errors */
  if (status != 0) lua_gc(L, LUA_GCCOLLECT, 0);
  return status;
}

static int lc_dofile (lua_State *L, const char *name) {
  int status = luaL_loadfile(L, name) || lc_docall(L, 0, 1);
  return lc_report(L, status);
}

static int lc_dostring (lua_State *L, const char *s, const char *name) {
  int status = luaL_loadbuffer(L, s, strlen(s), name) || lc_docall(L, 0, 1);
  return lc_report(L, status);
}

static int lc_handle_luainit (lua_State *L) {
  const char *init = getenv(LUA_INIT);
  if (init == NULL) return 0;  /* status OK */
  else if (init[0] == '@')
    return lc_dofile(L, init+1);
  else
    return lc_dostring(L, init, "=" LUA_INIT);
}


typedef struct {
  int c;
  const char ** v;
} lc_args_t;


/* create global arg table */
static void lc_createarg(lua_State * L, const lc_args_t * const args) {
  int i;
  lua_newtable(L);
  for (i=0; i < args->c; i++) {
    lua_pushstring(L, args->v[i]);
    lua_rawseti(L, -2, i);
  }
  lua_setglobal(L, "arg");
}


int lc_pmain_mod_nssm_rainbow_staff(lua_State * L) {
  luaL_openlibs(L);

  lua_pushcfunction(L, traceback);

  const int status1 = lc_handle_luainit(L);
  if (status1 != 0) return 0;

  /* note: IMPROVE: closure not always needed here */
  lua_newtable(L); /* closure table */
  lua_pushcclosure(L, lcf_main, 1);

  int status2 = lua_pcall(L, 0, 0, -2);
  if (status2 != 0) {
    const char * msg = lua_tostring(L,-1);
    if (msg == NULL) msg = "(error object is not a string)";
    fputs(msg, stderr);
  }
  return 0;
}


