local package_exclusions = 
{
	{ ["name"] = "3d_armor",["author"] = "stu"},
	{ ["name"] = "ambience",["author"] = "TenPlus1"},
	{ ["name"] = "areas",["author"] = "ShadowNinja"},
	{ ["name"] = "bakedclay",["author"] = "TenPlus1"},
	{ ["name"] = "basic_materials",["author"] = "VanessaE"},
	{ ["name"] = "biome_lib",["author"] = "VanessaE"},
	{ ["name"] = "bonemeal",["author"] = "TenPlus1"},
	{ ["name"] = "boost_cart",["author"] = "Krock"},
	{ ["name"] = "caverealms",["author"] = "HeroOfTheWinds"},
	{ ["name"] = "caverealms",["author"] = "Shara"},
	{ ["name"] = "cottages",["author"] = "Sokomine"},
	{ ["name"] = "currency",["author"] = "VanessaE"},
	{ ["name"] = "digilines",["author"] = "Jeija"},
	{ ["name"] = "ethereal",["author"] = "TenPlus1"},
	{ ["name"] = "intllib",["author"] = "kaeza"},
	{ ["name"] = "lucky_block",["author"] = "TenPlus1"},
	{ ["name"] = "mesecons",["author"] = "Jeija"},
	{ ["name"] = "mobs",["author"] = "TenPlus1"},
	{ ["name"] = "mobs_animal",["author"] = "TenPlus1"},
	{ ["name"] = "mobs_monster",["author"] = "TenPlus1"},
	{ ["name"] = "moreblocks",["author"] = "Calinou"},
	{ ["name"] = "moreores",["author"] = "Calinou"},
	{ ["name"] = "moresnow",["author"] = "Sokomine"},
	{ ["name"] = "moretrees",["author"] = "VanessaE"},
	{ ["name"] = "nether",["author"] = "PilzAdam"},
	{ ["name"] = "nssm",["author"] = "npx"},
	{ ["name"] = "pipeworks",["author"] = "VanessaE"},
	{ ["name"] = "plantlife_modpack",["author"] = "VanessaE"},
	{ ["name"] = "sfinv",["author"] = "rubenwardy"},
	{ ["name"] = "stairs",["author"] = "TenPlus1"},
	{ ["name"] = "subterrane",["author"] = "FaceDeer"},
	{ ["name"] = "technic",["author"] = "RealBadAngel"},
	{ ["name"] = "treasurer",["author"] = "Wuzzy"},
	{ ["name"] = "unifieddyes",["author"] = "VanessaE"},
	{ ["name"] = "unified_inventory",["author"] = "RealBadAngel"},
	{ ["name"] = "worldedit",["author"] = "sfan5"},
	{ ["name"] = "xconnected",["author"] = "Sokomine"},
	{ ["name"] = "xdecor",["author"] = "jp"},
}

return package_exclusions